### ISSUE TITLE
Cocoapods use_frameworks! 支持

### ISSUE THREAD

**Issue by winddpan** [netease-kit/nim-uikit-ios#140]
1.5.0及以上的Cocoapods已经支持```use_frameworks!```后的静态库依赖。
目前加入```use_frameworks!```关键词后```NIMKitDependency.h```编译会报错，只需简单处理一下即可编译通过。
希望简单修改一下，造福需要使用```use_frameworks!```的用户。

**Comment by emilyzyw** [comment]
多谢反馈，我们这边配置一下

**Comment by winddpan** [comment]
[https://github.com/netease-im/NIM_iOS_UIKit/pull/153/files](url) PR了半个月了，麻烦合并一下。

**Comment by winddpan** [comment]
[https://github.com/netease-im/NIM_iOS_UIKit/pull/153/files](url)

**Comment by winddpan** [comment]
> 有机会合并吗？我现在也是遇到一样的问题.

我这本地已经处理完用framework的方式引用了。需要改一个头文件和资源引用的地方的代码。PR了没反应。

**Comment by jinke5245** [comment]
#212
