### ISSUE TITLE
NIMKit 与 Masonry冲突

### ISSUE THREAD

**Issue by mikeeastin** [netease-kit/nim-uikit-ios#142]
NIMKit 与 Masonry冲突
1.因为NIMTimestampModel与MASConstraint都有- height方法
2.NIMSessionTableAdapter.m文件中的 -tableView:heightForRowAtIndexPath: 代理方法中用id 类型声明了modelInArray对象，在后面又直接条用了- height方法，导致冲突

**Comment by edwardzg** [comment]
我也遇到了这个问题，编译报错。我把modelInArray强转成了NIMTimestampModel*，先跑起来再看看。

**Comment by SeasonSheng** [comment]
遇到了同样的问题，NIMSessionTableAdapter.m 的81行，导致build报错。
`cellHeight = [modelInArray height];`

**Comment by lvcode** [comment]
不止一个冲突，看来得手动导入了
