### ISSUE TITLE
群聊音视频功能,多人群聊

### ISSUE THREAD

**Issue by xfy6238** [netease-kit/nim-uikit-ios#149]
在进行多人音视频功能时,需要显示各人的视频画面: - (void)onRemoteYUVReady:(NSData *)yuvData
                   width:(NSUInteger)width
                  height:(NSUInteger)height
                    from:(NSString *)user;  这个方法只返回了yuvData数据, 视频显示需要NTESGLView  而要使用它又必须集成ijksdl.  可问题是怎么集成?

**Comment by maketubotim** [comment]
ijksdl，你集成这个了吗
