### ISSUE TITLE
如何全局设置气泡图片，没找到对应的方法

### ISSUE THREAD

**Issue by jkwf** [netease-kit/nim-uikit-ios#157]
1、如何全局设置气泡图片，没找到对应的方法，只能用下面的方法一个一个的设置
[NIMKit sharedKit].config.leftBubbleSettings.textSetting.normalBackgroundImage = [UIImage imageNamed:@"chat_left"];

2、在NTESCellLayoutConfig类里设置内容距气泡的边距，会出现有的图片正常，有的图片边距不正常

3、怎么设置图片消息，图片的圆角

**Comment by emilyzyw** [comment]
1. 确实没有统一的背景图，因为一般不同类型消息背景也不一样吧
2. 第二个最好是有具体设置代码，否则不好判断
3. 图片消息圆角可以通过CAShapeLayer 去添加给你的imageView，这个 我们这边下个版本可以考虑添加到组件里做成可配置的

**Comment by ZexiFangkong** [comment]
@emilyzyw  
请问你们的气泡是通过什么设置的呀。
没找到相关实现emmmm
