### ISSUE TITLE
历史消息从自己服务器获取，该怎么展示？

### ISSUE THREAD

**Issue by lwy121810** [netease-kit/nim-uikit-ios#160]
我们现在要做一个历史消息类的展示，数据是从我们服务器获取，能使用该UI库嘛？能的话该怎么做？
p.s: 我们的消息类型比较少，只有文本，图片，后续可能会有语音类型

**Comment by sevenuncler** [comment]
可以参考下NIM Demo上的实现类:NTESSessionRemoteHistoryViewController
