### ISSUE TITLE
NIMSDK_LITE   pod install warning

### ISSUE THREAD

**Issue by ZexiFangkong** [netease-kit/nim-uikit-ios#171]
[!] 'NIMSDK_LITE' uses the unencrypted http protocol to transfer the Pod. Please be sure you're in a safe network with only trusted hosts in there. Please reach out to the library author to notify them of this security issue.

pod install 成功之后, 每次看到这个警告, 希望能修改一下。

**Comment by NicalDai** [comment]
这个不影响的
