### ISSUE TITLE
怎样自定义NIMInputToolBar

### ISSUE THREAD

**Issue by sunzhongliangde** [netease-kit/nim-uikit-ios#174]
聊天输入框这一块，我需要自定义按钮的图标，以及按钮的事件
这一块我找遍了文档也没有一个详细的说明，
我自己尝试去修改没有成功
self.toolBar = [[YGIMInputToolBar alloc] initWithFrame:CGRectMake(0, 0, self.view.yg_width, 0)];
    [self.sessionInputView.toolBar.voiceButton setImage:[UIImage imageNamed:@"IM_tel_icon"] forState:UIControlStateNormal];

**Comment by sevenuncler** [comment]
可以参考下- (void)updateVoiceBtnImages:(BOOL)selected
