### ISSUE TITLE
没人来谈一下依赖库的问题吗？

### ISSUE THREAD

**Issue by sunzhongliangde** [netease-kit/nim-uikit-ios#175]
os.resources = 'NIMKit/Resources/*.*'   
    os.dependency 'SDWebImage', '~> 4.2.2'  
    os.dependency 'Toast', '~> 3.0'         
    os.dependency 'M80AttributedLabel', '~> 1.6.3'       
    os.dependency 'TZImagePickerController', '~> 1.9.0'  

这些依赖库能不能去版本号，或者说你们手动引入第三方库加前缀。
做一个公共库，不应该再有任何的公共库引入并且指定版本号。

**Comment by LevinSun** [comment]
我是去掉了依赖库的版本号，目前跑下来没有问题。备注：我的是swift工程，引用NIM_UIKit源码包

**Comment by Bovvge** [comment]
keng

**Comment by chenxing890** [comment]
> 我是去掉了依赖库的版本号，目前跑下来没有问题。备注：我的是swift工程，引用NIM_UIKit源码包

能给个示例么. .   这破组件太坑了.          不是这里报错就是那里报错. .  完全跑不起来啊.

**Comment by jinke5245** [comment]
我更新了一下依赖库，并提交了 Pull Request ( #212 )。
希望官方可以追踪依赖库的更新，及时更新到最新提交。

```ruby
pod 'NIMKit', :git => 'https://github.com/jinke5245/NIM_iOS_UIKit.git'
```
