### ISSUE TITLE
请去掉 SDWebImage  和 TZImagePickerController 的依赖版本，保持最新版本

### ISSUE THREAD

**Issue by eternaljust** [netease-kit/nim-uikit-ios#181]
s.subspec 'Core' do |os|     
      os.resources = 'NIMKit/Resources/*.*'   
      os.dependency 'SDWebImage', '~> 4.2.2'  
      os.dependency 'Toast', '~> 3.0'         
      os.dependency 'M80AttributedLabel', '~> 1.6.3'       
      os.dependency 'TZImagePickerController', '~> 1.9.0'  
  end 

SDWebImage 最新版本 4.4.2
TZImagePickerController 最新版本 3.1.5
这两个常用的库为何要一直用低版本的？为何不保持最新版本？

**Comment by HaijunWei** [comment]
同问，项目里面用了高版本，难受

**Comment by tryEvething** [comment]
+1

**Comment by sunzhongliangde** [comment]
云信开发人员对于使用者的提问充耳不闻。都是掏钱用你们的sdk，有这么对待你们的衣食父母吗？

**Comment by newjia** [comment]
+1
[!] CocoaPods could not find compatible versions for pod "TZImagePickerController":
  In snapshot (Podfile.lock):
    TZImagePickerController (= 3.1.6)

  In Podfile:
    TZImagePickerController

    TZImagePickerController (~> 1.9.0)

Specs satisfying the `TZImagePickerController, TZImagePickerController (~> 1.9.0), TZImagePickerController (= 3.1.6)` dependency were found, but they required a higher minimum deployment target.

**Comment by MagicalGemini** [comment]
+1
SDWebImage锁定的版本好老，导致现在NIMKit和其他用到SDWebImage的第三方库版本冲突了

**Comment by iwantFB** [comment]
你们有什么解决的办法么？难道要自己下载导入？？

**Comment by tryEvething** [comment]
我的一种解决办法:

前往文件夹 ⇧⌘G

> ~/.cocoapods/repos/master/Specs

搜索NIMKit
我这的路径: 
> ~/.cocoapods/repos/master/Specs/4/c/a/NIMKit

找到最后一个最新版本,先备份一个NIMKit.podspec.json然后再修改

![](https://user-images.githubusercontent.com/18730979/56028826-97124c80-5d4b-11e9-9d1a-0e7c92a18e8b.png)
把依赖全删了,然后pod install --no-repo-update

最后再说说开发者,请动动手改下CocoaPods 依赖库,这要不了几分钟!

**Comment by iwantFB** [comment]
> 我的一种解决办法:
> 
> 前往文件夹 ⇧⌘G
> 
> > ~/.cocoapods/repos/master/Specs
> 
> 搜索NIMKit
> 我这的路径:
> 
> > ~/.cocoapods/repos/master/Specs/4/c/a/NIMKit
> 
> 找到最后一个最新版本,先备份一个NIMKit.podspec.json然后再修改
> 
> ![](https://user-images.githubusercontent.com/18730979/56028826-97124c80-5d4b-11e9-9d1a-0e7c92a18e8b.png)
> 把依赖全删了,然后pod install --no-repo-update
> 
> 最后再说说开发者,请动动手改下CocoaPods 依赖库,这要不了几分钟!

我现在的一个想法是fork了之后做一个自己的库

可能是因为改了库之后要改内部逻辑吧，毕竟能跑起来的东西为什么要改动呢？反正他们自己能跑起来就好

**Comment by ElfSundae** [comment]
我提交了 PR #186 #188 没人理..

**Comment by ElfSundae** [comment]
我合并到我的 fork 了

```ruby
pod 'NIMKit', :git => 'https://github.com/ElfSundae/NIM_iOS_UIKit.git', :tag => '2.11.6-patch1'
```

详见：https://github.com/ElfSundae/NIM_iOS_UIKit/releases

**Comment by tryEvething** [comment]
> 我合并到我的 fork 了
> 
> ```ruby
> pod 'NIMKit', :git => 'https://github.com/ElfSundae/NIM_iOS_UIKit.git', :tag => '2.11.6-patch1'
> ```
> 
> 详见：https://github.com/ElfSundae/NIM_iOS_UIKit/releases

去年的小bug，今年还没解决，心真的寒了，以后我使用都要看看是否还在更新

**Comment by Wenjie-Qin** [comment]
> 我的一种解决办法:
> 
> 前往文件夹 ⇧⌘G
> 
> > ~/.cocoapods/repos/master/Specs
> 
> 搜索NIMKit
> 我这的路径:
> 
> > ~/.cocoapods/repos/master/Specs/4/c/a/NIMKit
> 
> 找到最后一个最新版本,先备份一个NIMKit.podspec.json然后再修改
> 
> ![](https://user-images.githubusercontent.com/18730979/56028826-97124c80-5d4b-11e9-9d1a-0e7c92a18e8b.png)
> 把依赖全删了,然后pod install --no-repo-update
> 
> 最后再说说网易的开发者,请修改改下CocoaPods 依赖库,这要不了几分钟!

```
#if __has_include(<SDWebImage/SDWebImageCompat.h>)
#import <SDWebImage/SDWebImageCompat.h>
#elif __has_include("SDWebImageCompat.h")
#import "SDWebImageCompat.h"
#else
@import SDWebImage;   // 报错：Module 'SDWebImage' not found
#endif
```
我按照楼主的方法操作，再编译的时候报错“Module 'SDWebImage' not found”。不知道你们都是怎么解决的？

**Comment by ElfSundae** [comment]
@Wenjie-Qin 可以试试把 `Podfile` 中的：
```ruby
pod 'NIMKit'
```
换成：
```ruby
pod 'NIMKit', :git => 'https://github.com/ElfSundae/NIM_iOS_UIKit.git'
```
其他都不用改

**Comment by Wenjie-Qin** [comment]
> @Wenjie-Qin 可以试试把 `Podfile` 中的：
> 
> ```ruby
> pod 'NIMKit'
> ```
> 
> 换成：
> 
> ```ruby
> pod 'NIMKit', :git => 'https://github.com/ElfSundae/NIM_iOS_UIKit.git'
> ```
> 
> 其他都不用改

恩恩，刚开始就看到了你的这个方法。一直就是这么用的。不过因为业务需求，TZImagePickerController 这个第三方我们要增条几处改动，所以只能手动拖入项目中。现在使用您说的这个方法就会报错。所以准备改用另一种方案

**Comment by ElfSundae** [comment]
这种情况完全可以用 CocoaPods 完成，不建议手动添加第三方代码到项目。
Podfile 中可以使用自己的修改版，指定第三方库的源码路径为自己的修改版就行了。例如
```ruby
pod 'NIMKit', :git => 'https://github.com/ElfSundae/NIM_iOS_UIKit.git'
pod 'TZImagePickerController', :git => 'your/path'
```
除了 `:git`，还有其他类似的参数，例如 `:path`, `:podspec`, `:source` 等，可以参考 https://guides.cocoapods.org/syntax/podfile.html#pod
