### ISSUE TITLE
NIMInputEmoticonManager.m 第155行报错

### ISSUE THREAD

**Issue by idbeny** [netease-kit/nim-uikit-ios#190]
pod 导入NIMKit后运行报错
NIMInputEmoticonManager.m 第155行报错
reason: '*** -[NSBundle initWithURL:]: nil URL argument'
原因：
NSURL *url = [[NSBundle mainBundle] URLForResource:[[NIMKit sharedKit] emoticonBundleName]  withExtension:nil];
url为空导致下面的代码报错
NSBundle *bundle = [NSBundle bundleWithURL:url];
请问如何解决？

**Comment by wenlian2035** [comment]
我也遇到了，你怎么解决的？？

**Comment by opleonnn** [comment]
这里找不到 bundle，源码写的是从 mainBundle 里找资源。Swift 建议手动导入，具体看 Swift 集成文档
