### ISSUE TITLE
NIMCellLayoutConfig  avatarSize 方法无效

### ISSUE THREAD

**Issue by ZeroJian** [netease-kit/nim-uikit-ios#203]
### 问题描述
SDK 版本: 2.11.10
IMCellLayoutConfig  avatarSize 方法
设置用户图像大小无效, 设置后AvatarView大小变了, 但是上面的 imageView 还是默认的 40

**Comment by sevenuncler** [comment]
好的，会在2.12.0 版本修复这个问题
