### ISSUE TITLE
UI问题使用 - NIMSessionViewController  聊天这面出现 屏幕快照 2019-06-21 下午6.27.40

### ISSUE THREAD

**Issue by pttyy** [netease-kit/nim-uikit-ios#205]
### 问题检查清单

感谢您向我们提出问题，在提交问题之前，请确认以下事宜：

- [ ] 我已经阅读了组件文档: 

     [《项目结构介绍》](./Documents/nim_arch.md)

     [《界面排版自定义》](./Documents/nim_custom_ui.md)

     [《新消息类型集成》](./Documents/nim_custom_message.md)

     [《用户信息自定义》](./Documents/nim_userinfo.md)

     [《机器人消息排版指南》](./Documents/nim_robot.md)

- [ ] 我已经阅读了[常见问题](http://dev.netease.im/docs/product/%E9%80%9A%E7%94%A8/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98?#iOS%E7%89%88SDK), 但是找不到相关解决方案。

- [ ] 我已经阅读了[SDK 文档](http://dev.netease.im/docs/product/IM%E5%8D%B3%E6%97%B6%E9%80%9A%E8%AE%AF/SDK%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90/iOS%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90/%E6%A6%82%E8%A6%81%E4%BB%8B%E7%BB%8D), 但是找不到相关解决方案。
     
- [ ] 我已经搜索了[当前问题](https://github.com/netease-im/NIM_iOS_UIKit/issues?utf8=✓&q=is%3Aissue), 但是找不到相关解决方案。

#### 问题现象

[描述具体问题表现]

#### 是否重现

[重现此问题的步骤]

#### 其它备注

[在这里添加任何其他相关细节]

**Comment by pttyy** [comment]
![image](https://user-images.githubusercontent.com/13176599/59958076-8876ad00-94d3-11e9-9520-67981e7b5940.png)

**Comment by pttyy** [comment]
需要全局配置什么吗？

**Comment by zhanggenning** [comment]
你好，看你的UI里面有两个问题，不知道你具体问的是哪个问题：
1. 没有头像。<NIMCellLayoutConfig>里shouldShowAvatar：请返回YES。全局配置NIMKitSetting里showAvatar设置为YES（默认）
2. 文字气泡位置不对。请确定<NIMCellLayoutConfig>里contentSize：返回长度是否正确

因为不知道你这边是否是使用了NIMCellLayoutConfig，如果没有请替换成自带的NIMCellLayoutConfig再测试一下看是否会出现文字气泡位置不对的现象。如果方便的话，最好可以发送下出现问题的demo，一起调试一下。

**Comment by pttyy** [comment]
这个问题是因为你们的头像占位图名字改变了，导致路径找不到 bundle 里的图片是 DefaultAvatar 但代码写的是 default_avatar  ,出现这个原因可能还是版本的问题，我在上个问题已经提到了，希望你能看下，谢谢

**Comment by zhanggenning** [comment]
好的 因为这里一般头像都是使用服务端拉取的头像 没有注意到默认的占位图像 忽略了这个问题 我们下个版本修复这个问题。麻烦附上您上个问题所提到内容的链接，我们这边一起处理一下，谢谢

**Comment by fxxxchao** [comment]
还没解决吗？还是这样，没有自定义，就是跑demo
