### ISSUE TITLE
NIMUIKit/full 的 NIMSDK 与 官方demo的 NIMSDK 提供api 有缺少

### ISSUE THREAD

**Issue by pttyy** [netease-kit/nim-uikit-ios#206]
### 问题检查清单

感谢您向我们提出问题，在提交问题之前，请确认以下事宜：

- [ ] 我已经阅读了组件文档: 

     [《项目结构介绍》](./Documents/nim_arch.md)

     [《界面排版自定义》](./Documents/nim_custom_ui.md)

     [《新消息类型集成》](./Documents/nim_custom_message.md)

     [《用户信息自定义》](./Documents/nim_userinfo.md)

     [《机器人消息排版指南》](./Documents/nim_robot.md)

- [ ] 我已经阅读了[常见问题](http://dev.netease.im/docs/product/%E9%80%9A%E7%94%A8/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98?#iOS%E7%89%88SDK), 但是找不到相关解决方案。

- [ ] 我已经阅读了[SDK 文档](http://dev.netease.im/docs/product/IM%E5%8D%B3%E6%97%B6%E9%80%9A%E8%AE%AF/SDK%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90/iOS%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90/%E6%A6%82%E8%A6%81%E4%BB%8B%E7%BB%8D), 但是找不到相关解决方案。
     
- [ ] 我已经搜索了[当前问题](https://github.com/netease-im/NIM_iOS_UIKit/issues?utf8=✓&q=is%3Aissue), 但是找不到相关解决方案。

#### 问题现象

[描述具体问题表现]

#### 是否重现

[重现此问题的步骤]

#### 其它备注

[在这里添加任何其他相关细节]

**Comment by zhanggenning** [comment]
你好，请问是哪个版本的NIMKit出现这个问题的，我这边对比了最新的NIMKit里的sdk和我们官网的sdk的对外接口是一致的，没有发现缺少的现象，目前最新版本NIMKit是2.11.12，对应的sdk版本是6.6.0，如果发现旧版本有API缺少的现象，请及时更新到最新版本。

附：
NIMKit/Full 对应 官网完整版本的NIMSDK，包含IM即时通讯、信令、聊天室、音视频通话、互动白板、互动直播
NIMKit 或者 NIMKit/Lite 对应 官网基础版本的NIMSDK，包含IM即时通讯、信令、聊天室

**Comment by pttyy** [comment]
通过 pod 'NIMKit/Full' 下载  NIMKit是1.8.0，对应的sdk版本是4.1.0，跟你的 版本是不对

**Comment by pttyy** [comment]
执行 pod repo update 下载的 还是 NIMKit是1.8.0，对应的sdk版本是4.1.0 
![image](https://user-images.githubusercontent.com/13176599/60408277-d8025a80-9bf0-11e9-8cd5-0b817114d310.png)

**Comment by zhanggenning** [comment]
可能需要清理一下pod的搜索缓存，然后再更新一下 repo。参考一下：https://www.jianshu.com/p/b5e5cd053464
如果还是不行，请确定这边的pod repo update的源是最新的源，因为从你的这边版本来看，应该是repo比较旧了。

**Comment by pttyy** [comment]
好的，明天上班再看下，谢谢，由于我司项目在调研IM框架，看了文档目前觉得网易云信比较适合，后续开通其他功能可能需要跟云信技术对接一下，你方便提供一下联系方式吗？


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: zhanggenning <notifications@github.com>
发送时间: 2019年7月2日 22:37
收件人: netease-im/NIM_iOS_UIKit <NIM_iOS_UIKit@noreply.github.com>
抄送: Eddy <2497101274@qq.com>, Author <author@noreply.github.com>
主题: 回复：[netease-im/NIM_iOS_UIKit] NIMUIKit/full 的 NIMSDK 与 官方demo的 NIMSDK 提供api 有缺少 (#206)




可能需要清理一下pod的搜索缓存，然后再更新一下 repo。参考一下：https://www.jianshu.com/p/b5e5cd053464
 如果还是不行，请确定这边的pod repo update的源是最新的源，因为从你的这边版本来看，应该是repo比较旧了。

**Comment by pttyy** [comment]
我已经是最新的源，还是下载不到最新的云信 sdk
![image](https://user-images.githubusercontent.com/13176599/60556875-c5fdf480-9d75-11e9-8ff6-6d39ff6b0b56.png)

**Comment by zhanggenning** [comment]
使用https://rubygems.org/ 源试一试

**Comment by zhanggenning** [comment]
使用https://rubygems.org/源试一试，可以加一下我的QQ 315310593
