### ISSUE TITLE
NIM_iOS_UIKit-master下下来之后，pod install，运行的时候报错

### ISSUE THREAD

**Issue by taidypanda** [netease-kit/nim-uikit-ios#213]
模拟器可以编译通过，但是无法安装
模拟器报：This app could not be installed at this time.
Failed to load Info.plist from bundle at path /Users/name/Library/Developer/CoreSimulator/Devices/007A4125-CBA6-4B0F-A7FE-778F6E9C78F8/data/Library/Caches/com.apple.mobile.installd.staging/temp.mnTjdb/extracted/DemoApplication.app/Frameworks/NIMSDK.framework

真机编译不通过：
:-1: Undefined symbol: _OBJC_CLASS_$_NIMMessageApnsMemberOption
:-1: Undefined symbol: _OBJC_CLASS_$_NIMMessageSearchOption
:-1: Undefined symbol: _OBJC_CLASS_$_NIMRobotObject
:-1: Undefined symbol: _OBJC_CLASS_$_NIMImageOption
:-1: Undefined symbol: _OBJC_CLASS_$_NIMImageObject
:-1: Undefined symbol: _OBJC_CLASS_$_NIMNotificationObject
:-1: Undefined symbol: _OBJC_CLASS_$_NIMVideoObject
:-1: Undefined symbol: _OBJC_CLASS_$_NIMMessageSetting
:-1: Undefined symbol: _OBJC_CLASS_$_NIMMessageReceipt
:-1: Undefined symbol: _NIMNOSSceneTypeMessage
:-1: Undefined symbol: _OBJC_CLASS_$_NIMUpdateTeamInfoAttachment
:-1: Undefined symbol: _OBJC_CLASS_$_NIMMessage
:-1: Undefined symbol: _OBJC_CLASS_$_NIMMessageChatroomExtension
:-1: Undefined symbol: _OBJC_CLASS_$_NIMAudioObject
:-1: Undefined symbol: _OBJC_CLASS_$_NIMLocationObject
:-1: Undefined symbol: _OBJC_CLASS_$_NIMSDK
:-1: Undefined symbol: _OBJC_CLASS_$_NIMMuteTeamMemberAttachment
:-1: Undefined symbol: _NIMNOSSceneTypeAvatar
:-1: Undefined symbol: _OBJC_CLASS_$_NIMCustomObject
:-1: Undefined symbol: _OBJC_CLASS_$_NIMSession

环境：xcode 10.2.1

**Comment by taidypanda** [comment]
我新建了一个空的工程，只集成一个pod 'NIMKit'，然后pod install ，也不能运行

**Comment by ElfSundae** [comment]
```sh
cd NIM_iOS_UIKit/Example
pod update
open DemoApplication.xcworkspace
```

**Comment by zhanggenning** [comment]
看报错好像是pod我们sdk的时候失败了，我们这边测试最新版的是没有问题的，要不把完整的pod过程信息发一下 我们看一看？

**Comment by taidypanda** [comment]
> 看报错好像是pod我们sdk的时候失败了，我们这边测试最新版的是没有问题的，要不把完整的pod过程信息发一下 我们看一看？

$ pod install 
Ignoring RedCloth-4.2.9 because its extensions are not built. Try: gem pristine RedCloth --version 4.2.9
Ignoring fast-stemmer-1.0.2 because its extensions are not built. Try: gem pristine fast-stemmer --version 1.0.2
Ignoring ffi-1.9.23 because its extensions are not built. Try: gem pristine ffi --version 1.9.23
Ignoring posix-spawn-0.3.13 because its extensions are not built. Try: gem pristine posix-spawn --version 0.3.13
Ignoring rdiscount-2.2.0.1 because its extensions are not built. Try: gem pristine rdiscount --version 2.2.0.1
Ignoring redcarpet-3.4.0 because its extensions are not built. Try: gem pristine redcarpet --version 3.4.0
Ignoring yajl-ruby-1.2.3 because its extensions are not built. Try: gem pristine yajl-ruby --version 1.2.3
Analyzing dependencies
Fetching podspec for `NIMKit` from `../`
Downloading dependencies
Using M80AttributedLabel (1.6.3)
Using NIMKit (2.11.14)
Using NIMSDK_LITE (6.6.7)
Using SDWebImage (4.4.7)
Using TZImagePickerController (3.0.9)
Using Toast (3.1.0)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 6 total pods installed.

[!] [!] Xcodeproj doesn't know about the following attributes {"inputFileListPaths"=>[], "outputFileListPaths"=>[]} for the 'PBXShellScriptBuildPhase' isa.
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new
