### ISSUE TITLE
聊天室调用插入消息时候，偶尔会报错，报错的断点断在NIMSessionLayoutImpl类的 [self.tableView endUpdates]这一句代码，具体错误reason: 'Invalid update: invalid number of rows in section 0，而聊天室这边的消息基本上都是该库在管理，求尽快解答

### ISSUE THREAD

**Issue by OLeGeB** [netease-kit/nim-uikit-ios#215]
### 问题检查清单

感谢您向我们提出问题，在提交问题之前，请确认以下事宜：

- [x] 我已经阅读了组件文档: 

     [《项目结构介绍》](./Documents/nim_arch.md)

     [《界面排版自定义》](./Documents/nim_custom_ui.md)

     [《新消息类型集成》](./Documents/nim_custom_message.md)

     [《用户信息自定义》](./Documents/nim_userinfo.md)

     [《机器人消息排版指南》](./Documents/nim_robot.md)

- [x] 我已经阅读了[常见问题](http://dev.netease.im/docs/product/%E9%80%9A%E7%94%A8/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98?#iOS%E7%89%88SDK), 但是找不到相关解决方案。

- [x] 我已经阅读了[SDK 文档](http://dev.netease.im/docs/product/IM%E5%8D%B3%E6%97%B6%E9%80%9A%E8%AE%AF/SDK%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90/iOS%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90/%E6%A6%82%E8%A6%81%E4%BB%8B%E7%BB%8D), 但是找不到相关解决方案。
     
- [x] 我已经搜索了[当前问题](https://github.com/netease-im/NIM_iOS_UIKit/issues?utf8=✓&q=is%3Aissue), 但是找不到相关解决方案。

#### 问题现象

[描述具体问题表现]

#### 是否重现

[重现此问题的步骤]

#### 其它备注

[在这里添加任何其他相关细节]

**Comment by zhanggenning** [comment]
这种情况应该是数据源与视图不一致导致的，具体原因看一下是不是再其他线程动了数据源导致视图和数据源不一致

**Comment by OLeGeB** [comment]
我看到你们UIKIT内部并没有让所有的对数据源的操作用主线程进行守护，您这边的意思我只要涉及到往视图上添加消息的地方，都要放到主线程中去执行，是这个意思吧

**Comment by zhanggenning** [comment]
是的 正常来说 更新数据源和更新UI应该是都需要在主线程的

**Comment by OLeGeB** [comment]
你好，按照你之前说的，所有更新数据源的方法放到主线程中，崩溃率下降了很多，但是最近我通过bugly看到还是有这方面的问题，而我确保更新数据源的方法都已放到主线程中，我这边刚进入聊天室的时候，会拉取固定数量的聊天室历史信息，然后去刷新数据源。我这边考虑了一下 是不是因为我没有判断历史数据是否为空数据的数组导致的。这边您能加一下QQ：4372786，方便及时的联系，万分感谢。下面是问题的描述

attempt to insert row 0 into section 0, but there are only 0 rows in section 0 after the update
-[NIMSessionLayoutImpl insert:animated:] (NIMSessionLayoutImpl.m:243)
--
 -[NIMSessionInteractorImpl processChatroomMessageModels] (NIMSessionInteractorImpl.m:603)
 __48-[NIMSessionInteractorImpl addChatroomMessages:]_block_invoke_2 (NIMSessionInteractorImpl.m:140)

**Comment by mengshusheng** [comment]
你好，我现在也遇到这个崩溃，出现的场景是进入聊天界面，在获取一定数量的历史记录，这个时间内如果对方一直快速的发大量信息，会崩溃，我检查了 数据更新都是在主程里进行的啊

**Comment by NullWorld** [comment]
0.1秒的同步时间完全不够。。。哈哈哈哈
