### ISSUE TITLE
输入框输入到第二行时高度出现bug

### ISSUE THREAD

**Issue by iToby** [netease-kit/nim-uikit-ios#224]
![IMG_0189](https://user-images.githubusercontent.com/8199014/63103866-7d5e6b80-bfb0-11e9-8759-b6c4cc54a794.jpg)
输入框第二行时高度出现bug，见图，偏上，再输入一个字就好了

**Comment by ElfSundae** [comment]
输入文字的 textView 在换行时（改变 frame.height 时） contentOffset 有问题

**Comment by iToby** [comment]
> 输入文字的 textView 在换行时（改变 frame.height 时） contentOffset 有问题

有解决方案吗？

**Comment by wangyong-numob** [comment]
我也遇到了这个问题。有修改办法吗

**Comment by ElfSundae** [comment]
最新版本已解决此问题。
