### ISSUE TITLE
预加载表情崩溃 preloadEmoticonResource, nim_emoticonInKit ,NSInternalInconsistencyException  Need an imageRef

### ISSUE THREAD

**Issue by iToby** [netease-kit/nim-uikit-ios#228]
### 问题检查清单

感谢您向我们提出问题，在提交问题之前，请确认以下事宜：

- [x] 我已经阅读了组件文档: 

     [《项目结构介绍》](./Documents/nim_arch.md)

     [《界面排版自定义》](./Documents/nim_custom_ui.md)

     [《新消息类型集成》](./Documents/nim_custom_message.md)

     [《用户信息自定义》](./Documents/nim_userinfo.md)

     [《机器人消息排版指南》](./Documents/nim_robot.md)

- [x] 我已经阅读了[常见问题](http://dev.netease.im/docs/product/%E9%80%9A%E7%94%A8/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98?#iOS%E7%89%88SDK), 但是找不到相关解决方案。

- [x] 我已经阅读了[SDK 文档](http://dev.netease.im/docs/product/IM%E5%8D%B3%E6%97%B6%E9%80%9A%E8%AE%AF/SDK%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90/iOS%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90/%E6%A6%82%E8%A6%81%E4%BB%8B%E7%BB%8D), 但是找不到相关解决方案。
     
- [x] 我已经搜索了[当前问题](https://github.com/netease-im/NIM_iOS_UIKit/issues?utf8=✓&q=is%3Aissue), 但是找不到相关解决方案。

#### 问题现象

不了解现象，应该是崩溃，Bugly系统反馈
设备机型 iPhone 6s
系统版本 13.0 (17A5565b)

#### 是否重现

是，iOS 13系统下多次上报

#### 其它备注

[在这里添加任何其他相关细节]
Bugly反馈：
设备机型 iPhone 6s
系统版本 13.0 (17A5565b)
<img width="984" alt="WX20190824-083713@2x" src="https://user-images.githubusercontent.com/8199014/63630206-d7af9a00-c64a-11e9-95d6-cbb827f3478a.png">

**Comment by iToby** [comment]
该问题在 13.1 也经常复现

**Comment by ElfSundae** [comment]
重现步骤？

**Comment by iToby** [comment]
不知道复现步骤，腾讯Bugly上报的

**Comment by iToby** [comment]
> 重现步骤？

不确定复现步骤，腾讯Bugly上报的

**Comment by zhanggenning** [comment]
2.12.7 版本上我先对这个方法进行一下基本的防御

**Comment by zhanggenning** [comment]
https://gist.github.com/gali8/f4bbd5ad6421ea3c2be063dc50b04e9d
因为没有复现，根据上面网页上的描述，可能是iOS13对imageNamed：做了防空保护导致的崩溃，我先在nim_emoticonInKit:方法上做如下保护，后续如果再复现，再进一步排查
+ (UIImage *)nim_emoticonInKit:(NSString *)imageName
{
    if (imageName.length == 0) {
        return nil;
    }
    NSString *name = [[[NIMKit sharedKit] emoticonBundleName] stringByAppendingPathComponent:imageName];
    if (name.length == 0) {
        return nil;
    }
    NSFileManager *fm =[NSFileManager defaultManager];
    BOOL isDir = NO;
    if (![fm fileExistsAtPath:name isDirectory:&isDir] || isDir) {
        return nil;
    } else {
        UIImage *image = [UIImage imageNamed:name];
        return image;
    }
}

**Comment by iToby** [comment]
> * NSFileManager *fm =[NSFileManager defaultManager];
>   BOOL isDir = NO;
>   if (![fm fileExistsAtPath:name isDirectory:&isDir] || isDir) {
>   return nil;
>   }

大佬，使用这段代码有些表情加载不出来，貌似是文件判断这个地方的问题

**Comment by ElfSundae** [comment]
@zhanggenning 强烈建议不要这么处理。如果是因为参数 `nil` 或文件不存在而导致的问题应该让调用方检查代码，而不是屏蔽（隐藏）这些错误的调用。
如果要检查参数合法性，可以使用 `NSAssert` `NSParameterAssert` 等方法，让有问题的代码在开发时就被发现并修复。

**Comment by ElfSundae** [comment]
@iToby 部分表情没加载： https://github.com/netease-im/NIM_iOS_UIKit/pull/227

**Comment by zhanggenning** [comment]
@ElfSundae 这个不算屏蔽或者隐藏，只是做了入参的基本防护，用户可以根据返回值nil来判断当前有没有成功加载图片。我可以将异常的检测结果用你推荐的方式告知一下调用者。

**Comment by ElfSundae** [comment]
@zhanggenning 嗯，可是 UIImage.imageNamed 方法已经对其参数做了「防护」了，传入 `nil` 或者一个不存在的文件名时返回 `nil` 。
如果我们的 `nim_imageNamed` 只是传递 `name` 参数给另外一个方法 `UIImage.imageNamed` , 而 `nim_imageNamed` 内部并没有使用 `name` 这个参数的话，我觉得这种情况下就不要过度防护了。

@iToby 另外，关于这个 crash，应该是这个原因： https://medium.com/@danielegaliotto/solved-nsinternalinconsistencyexception-reason-need-an-imageref-ios13-c79103b4e3f7

**Comment by iToby** [comment]
谢谢 @zhanggenning 和 @ElfSundae 。不过项目没有用到 Color Set 。

**Comment by jakajacky** [comment]
@iToby 您好，请问后来这个问题怎么解决的😄
