### ISSUE TITLE
适配ios13 有更新吗？

### ISSUE THREAD

**Issue by bingolib** [netease-kit/nim-uikit-ios#237]
### 问题检查清单

感谢您向我们提出问题，在提交问题之前，请确认以下事宜：

- [ ] 我已经阅读了组件文档: 

     [《项目结构介绍》](./Documents/nim_arch.md)

     [《界面排版自定义》](./Documents/nim_custom_ui.md)

     [《新消息类型集成》](./Documents/nim_custom_message.md)

     [《用户信息自定义》](./Documents/nim_userinfo.md)

     [《机器人消息排版指南》](./Documents/nim_robot.md)

- [ ] 我已经阅读了[常见问题](http://dev.netease.im/docs/product/%E9%80%9A%E7%94%A8/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98?#iOS%E7%89%88SDK), 但是找不到相关解决方案。

- [ ] 我已经阅读了[SDK 文档](http://dev.netease.im/docs/product/IM%E5%8D%B3%E6%97%B6%E9%80%9A%E8%AE%AF/SDK%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90/iOS%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90/%E6%A6%82%E8%A6%81%E4%BB%8B%E7%BB%8D), 但是找不到相关解决方案。
     
- [ ] 我已经搜索了[当前问题](https://github.com/netease-im/NIM_iOS_UIKit/issues?utf8=✓&q=is%3Aissue), 但是找不到相关解决方案。

#### 问题现象

[描述具体问题表现]

#### 是否重现

[重现此问题的步骤]

#### 其它备注

[在这里添加任何其他相关细节]

**Comment by chenxing890** [comment]
iOS 13 在运行时崩溃

file:NIMDat2019-09-24 00:38:11.350890+0800 xxxx [1052:343198] Can't end BackgroundTask: no background task exists with identifier 3 (0x3), or it may have already been ended. Break in UIApplicationEndBackgroundTaskError() to debug.

**Comment by ElfSundae** [comment]
你们在 iOS 13 上遇到啥问题了？我这没发现需要适配的..

**Comment by ElfSundae** [comment]
@chenxing890 `file:NIMDat2019-09-24` 哪个文件? 
NIMKit 没使用 `endBackgroundTask`

**Comment by bingolib** [comment]
Assertion failure in -[UINavigationController _popNavigationBar:item:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKitCore/UIKit-3899.13.13/UINavigationController.m:8520 
哪位大佬可以帮忙看下这是什么问题。我把自定义导航栏的相关代码都注释掉了 还是不行。一点返回按钮就崩了

**Comment by fdyhgjg** [comment]
ios13系统下 预览视频消息的控制器里面的MPMoviePlayerController在ios13已经不能用了

**Comment by zhanggenning** [comment]
@wxwlcp 这是因为iOS13上如果使用pushkit就一定要链接callkit，如果你这边不使用callkit请把NTESAppDelegate中关于pushkit注册部分代码注释掉即可
//    PKPushRegistry *pushRegistry = [[PKPushRegistry alloc] initWithQueue:dispatch_get_main_queue()];
//    pushRegistry.delegate = self;
//    pushRegistry.desiredPushTypes = [NSSet setWithObject:PKPushTypeVoIP];

**Comment by zhanggenning** [comment]
@fdyhgjg 好的因为MPMoviePlayerController只在demo上有使用到，因此没有即时替换，我们会在NIMKit 2.12.7版本上进行更换，谢谢提醒

**Comment by zhanggenning** [comment]
@bingolib 因为不知道你具体都注释了哪些代码，看一下代码里的几个关于navbar的swizzling类别,看看是不是那个影响的

**Comment by walkmanaly** [comment]
> 你们在 iOS 13 上遇到啥问题了？我这没发现需要适配的..

iOS13的devicetoken格式变了，导致收不到APN推送

**Comment by Sxiaobai** [comment]
> Assertion failure in -[UINavigationController _popNavigationBar:item:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKitCore/UIKit-3899.13.13/UINavigationController.m:8520
> 哪位大佬可以帮忙看下这是什么问题。我把自定义导航栏的相关代码都注释掉了 还是不行。一点返回按钮就崩了

最后咋解决的呢 UINavigationBarDelegate？
