### ISSUE TITLE
ios13系统下收不到推送，能升级下SDK吗？

### ISSUE THREAD

**Issue by fdyhgjg** [netease-kit/nim-uikit-ios#241]
### 问题检查清单

感谢您向我们提出问题，在提交问题之前，请确认以下事宜：

- [ ] 我已经阅读了组件文档: 

     [《项目结构介绍》](./Documents/nim_arch.md)

     [《界面排版自定义》](./Documents/nim_custom_ui.md)

     [《新消息类型集成》](./Documents/nim_custom_message.md)

     [《用户信息自定义》](./Documents/nim_userinfo.md)

     [《机器人消息排版指南》](./Documents/nim_robot.md)

- [ ] 我已经阅读了[常见问题](http://dev.netease.im/docs/product/%E9%80%9A%E7%94%A8/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98?#iOS%E7%89%88SDK), 但是找不到相关解决方案。

- [ ] 我已经阅读了[SDK 文档](http://dev.netease.im/docs/product/IM%E5%8D%B3%E6%97%B6%E9%80%9A%E8%AE%AF/SDK%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90/iOS%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90/%E6%A6%82%E8%A6%81%E4%BB%8B%E7%BB%8D), 但是找不到相关解决方案。
     
- [ ] 我已经搜索了[当前问题](https://github.com/netease-im/NIM_iOS_UIKit/issues?utf8=✓&q=is%3Aissue), 但是找不到相关解决方案。

#### 问题现象

[描述具体问题表现]

#### 是否重现

[重现此问题的步骤]

#### 其它备注

[在这里添加任何其他相关细节]

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo作者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA

**Comment by zhanggenning** [comment]
你好，如果你使用的是6.9.1之前的sdk版本，因为没有做token的消息解析iOS13的解析适配，所以是收不到推送的，你可以在外部自行解析之后，传进来，注意字符串解析之后通过(NSData *)token的方式直接将字符串传进来，不要使用initWithData:encoding:方式转换。这样就可以了，具体的token iOS13 解析方式看一下网上有很多，可以参考一下。

**Comment by walkmanaly** [comment]
> 你好，如果你使用的是6.9.1之前的sdk版本，因为没有做token的消息解析iOS13的解析适配，所以是收不到推送的，你可以在外部自行解析之后，传进来，注意字符串解析之后通过(NSData *)token的方式直接将字符串传进来，不要使用initWithData:encoding:方式转换。这样就可以了，具体的token iOS13 解析方式看一下网上有很多，可以参考一下。

[[NIMSDK sharedSDK] updateApnsToken:只提供了一个方法配置token，它内部做的转换，我们怎么配置？

**Comment by walkmanaly** [comment]
> 你好，如果你使用的是6.9.1之前的sdk版本，因为没有做token的消息解析iOS13的解析适配，所以是收不到推送的，你可以在外部自行解析之后，传进来，注意字符串解析之后通过(NSData *)token的方式直接将字符串传进来，不要使用initWithData:encoding:方式转换。这样就可以了，具体的token iOS13 解析方式看一下网上有很多，可以参考一下。

[[NIMSDK sharedSDK] updateApnsToken:只提供了一个方法配置token，它内部做的转换，请问我们怎么配置？

**Comment by ElfSundae** [comment]
@walkmanaly  把 AppDelegate 回调里的 deviceToken 直接传给 NIMSDK 就行了
```objc
- (void)application:(UIApplication *)app 
    didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken
{
    [[NIMSDK sharedSDK] updateApnsToken:deviceToken];
}
```

**Comment by walkmanaly** [comment]
> @walkmanaly  把 AppDelegate 回调里的 deviceToken 直接传给 NIMSDK 就行了
> ```objc
> - (void)application:(UIApplication *)app 
>     didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken
> {
>     [[NIMSDK sharedSDK] updateApnsToken:deviceToken];
> }
> ```

在iOS13不行哦，iOS以下的系统可以收到推送

**Comment by walkmanaly** [comment]
> > @walkmanaly  把 AppDelegate 回调里的 deviceToken 直接传给 NIMSDK 就行了
> > ```objc
> > - (void)application:(UIApplication *)app 
> >     didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken
> > {
> >     [[NIMSDK sharedSDK] updateApnsToken:deviceToken];
> > }
> > ```
> 
> 在iOS13不行哦，iOS13以下的系统可以收到推送


https://stackoverflow.com/questions/57839723/does-ios-13-has-new-way-of-getting-device-notification-token
因为iOS13的Devicetoken格式变了

**Comment by ElfSundae** [comment]
@walkmanaly 你用的最新版的 SDK 吗？

**Comment by walkmanaly** [comment]
> @walkmanaly 你用的最新版的 SDK 吗？

我直接pod ‘NIMKit’ 的。请问需要制定版本吗

**Comment by ElfSundae** [comment]
不需要指定版本，但是要执行 `pod update NIMKit` 才能更新到最新版的 SDK 。你看下 Podfile.lock 里 NIMSDK_LITE 的版本号

**Comment by walkmanaly** [comment]
> 不需要指定版本，但是要执行 `pod update NIMKit` 才能更新到最新版的 SDK 。你看下 Podfile.lock 里 NIMSDK_LITE 的版本号

请问最新版本是NIMKit (2.2.1)吗

**Comment by ElfSundae** [comment]
NIMKit 最新版是 2.12.6，NIMSDK 最新版是 6.10.0  [NIMKit.podspec.json](https://github.com/CocoaPods/Specs/blob/master/Specs/4/c/a/NIMKit/2.12.6/NIMKit.podspec.json)

**Comment by walkmanaly** [comment]
> 不需要指定版本，但是要执行 `pod update NIMKit` 才能更新到最新版的 SDK 。你看下 Podfile.lock 里 NIMSDK_LITE 的版本号

感谢回复。请问一下另外一个问题，SDK有没有获取一个成员在群里发言的计数统计接口呢

**Comment by ElfSundae** [comment]
@walkmanaly 我没用过群聊，看了下没有此类接口。你的应用如果支持服务端消息同步的话，建议看看云信服务端接口看有没有。

如果只是本地消息的话，给你提供几个思路。
方案1：有个搜索消息的接口可以查询到某用户的所有消息，从而得到发言计数：
```objc
NIMSession *session = [NIMSession session:@"group_id" type:NIMSessionTypeTeam];

NIMMessageSearchOption *option = [NIMMessageSearchOption new];
option.limit = 0;
option.allMessageTypes = YES;
option.fromIds = @[ @"from_user_id" ];

[NIMSDK.sharedSDK.conversationManager searchMessages:session
                                              option:option
                                              result:^(NSError * _Nullable error, NSArray<NIMMessage *> * _Nullable messages) {
    NSLog(@"%ld", messages.count);
}];
```
- 这个接口是搜索并返回消息对象 NIMMessage ，如果要查询的人多、或者某些人发的消息太多的话，可能会因为消息量太大导致慢、耗内存。
- `fromIds` 可以传数组，一次性查询多个用户的消息，然后在查询结果里统计每个用户的消息数。
- 建议在子线程执行搜索和统计。

方案2：使用 SQLite 函数或者 FMBD 或者 WCDB 直接从数据库里查询。
```sql
SELECT COUNT(*) FROM msg_group_1 where msg_from_id == 'user_id'
```

方案3：在 SDK 收发消息和删除消息的回调里，自己维护并缓存每个人的消息数。
方案4：调用 SDK 相关私有类，执行 SQL 查询，比如 NIMSessionDB, NIMDatabase 等，你自己研究吧。

**Comment by zhanggenning** [comment]
@walkmanaly 请仔细看一下我的回复，6.9.1之前的sdk版本需要自己外部解析好token传进来，6.9.1之后的直接传进来就行了，就调用[[NIMSDK sharedSDK] updateApnsToken:deviceToken]; 这个方法，解析好的字符串直接强转成data传进来即可。

**Comment by walkmanaly** [comment]
> @walkmanaly 请仔细看一下我的回复，6.9.1之前的sdk版本需要自己外部解析好token传进来，6.9.1之后的直接传进来就行了，就调用[[NIMSDK sharedSDK] updateApnsToken:deviceToken]; 这个方法，解析好的字符串直接强转成data传进来即可。

嗯嗯，我更新pod后可以了，谢谢

**Comment by walkmanaly** [comment]
> @walkmanaly 我没用过群聊，看了下没有此类接口。你的应用如果支持服务端消息同步的话，建议看看云信服务端接口看有没有。
> 
> 如果只是本地消息的话，给你提供几个思路。
> 方案1：有个搜索消息的接口可以查询到某用户的所有消息，从而得到发言计数：
> 
> ```objc
> NIMSession *session = [NIMSession session:@"group_id" type:NIMSessionTypeTeam];
> 
> NIMMessageSearchOption *option = [NIMMessageSearchOption new];
> option.limit = 0;
> option.allMessageTypes = YES;
> option.fromIds = @[ @"from_user_id" ];
> 
> [NIMSDK.sharedSDK.conversationManager searchMessages:session
>                                               option:option
>                                               result:^(NSError * _Nullable error, NSArray<NIMMessage *> * _Nullable messages) {
>     NSLog(@"%ld", messages.count);
> }];
> ```
> 
> * 这个接口是搜索并返回消息对象 NIMMessage ，如果要查询的人多、或者某些人发的消息太多的话，可能会因为消息量太大导致慢、耗内存。
> * `fromIds` 可以传数组，一次性查询多个用户的消息，然后在查询结果里统计每个用户的消息数。
> * 建议在子线程执行搜索和统计。
> 
> 方案2：使用 SQLite 函数或者 FMBD 或者 WCDB 直接从数据库里查询。
> 
> ```sql
> SELECT COUNT(*) FROM msg_group_1 where msg_from_id == 'user_id'
> ```
> 
> 方案3：在 SDK 收发消息和删除消息的回调里，自己维护并缓存每个人的消息数。
> 方案4：调用 SDK 相关私有类，执行 SQL 查询，比如 NIMSessionDB, NIMDatabase 等，你自己研究吧。

感谢详细的回复

**Comment by walkmanaly** [comment]
请问一下，单个群消息免打扰如何设置？（设置免打扰之后，这群不接收通知）后台说没有相应的接口，SDK我也没找到。

**Comment by ElfSundae** [comment]
搜索 updateNotifyState

**Comment by walkmanaly** [comment]
> 搜索 updateNotifyState

感谢感谢，（群聊）置顶的API有吗orz

**Comment by ElfSundae** [comment]
sessionListVC 里有个 sort 方法，自定义排序，把要置顶的 recentSession 排到最上面

Best Regards,
---------------------
Elf Sundae
https://0x123.com

**Comment by ElfSundae** [comment]
customSortRecents 方法，

**Comment by ElfSundae** [comment]
自己保存置顶属性，或者调用 recentSession.localExt 和 conversationManager.updateRecentLocalExt 读写置顶属性。在 sessionListViewController 的 customSortRecents 里根据置顶属性排序

**Comment by walkmanaly** [comment]
@ElfSundae 请问一下，群聊中用户昵称在不同群里显示不同昵称，该怎么设置呢

**Comment by ElfSundae** [comment]
```objc
// 获取群成员信息
NIMTeamMember *member = [NIMSDK.sharedSDK.teamManager
                            teamMember:uid
                                inTeam:session.sessionId];
member.nickname;

// 更新成员群昵称
[[NIMSDK sharedSDK].teamManager updateUserNick:userId 
                                       newNick:nickname 
                                        inTeam:session.sessionId
                                    completion:
```

**Comment by walkmanaly** [comment]
> ```objc
> // 获取群成员信息
> NIMTeamMember *member = [NIMSDK.sharedSDK.teamManager
>                             teamMember:uid
>                                 inTeam:session.sessionId];
> member.nickname;
> 
> // 更新成员群昵称
> [[NIMSDK sharedSDK].teamManager updateUserNick:userId 
>                                        newNick:nickname 
>                                         inTeam:session.sessionId
>                                     completion:
> ```

![WechatIMG7](https://user-images.githubusercontent.com/13470043/68991342-b7355b80-0898-11ea-953b-3216e1a9e6ab.png)
2个红框代表用户在群聊里等级，怎么做？

**Comment by ElfSundae** [comment]
自己维护用户等级信息；或者调用 NIMSDK.teamManager 的 updateMyCustomInfo 更新，NIMTeamMember.customInfo 读取自定义属性，这个自定义属性里保存用户在群里的等级或其他信息。

**Comment by ElfSundae** [comment]
自己维护用户等级信息；或者调用 NIMSDK.teamManager 的 updateMyCustomInfo 更新，NIMTeamMember.customInfo 读取自定义属性，这个自定义属性里保存用户在群里的等级或其他信息。

界面显示有很多方法，NIMKit 也提供了扩展。NIMKit.layoutConfig 里有个 customViews 方法，返回要添加的自定义view 。
或者 swizzle NIMMessageCell initWithStyle 方法里添加用户等级 view ，layoutSubviews 里布局等级 view ，让等级view.x = nameLabel.x; nameLabel.x =  CGRectGetMaxX(levelView.frame) + padding ，levelView 可以是 label 或 imageView ，看你需求了。
如果等级是文字，也可以和显示昵称的 nameLabel 共用一个控件，只需 swizzle NIMMessageCell 的 refresh 方法，设置 nameLabel 的 attributedText 属性为 `等级+ nameLabel.text` 即可，布局不用管。

**Comment by walkmanaly** [comment]
@ElfSundae 
<img width="513" alt="屏幕快照 2019-11-19 下午7 58 41" src="https://user-images.githubusercontent.com/13470043/69144977-8870ec80-0b07-11ea-8190-74d584ebc7d0.png">
<img width="505" alt="屏幕快照 2019-11-19 下午7 59 26" src="https://user-images.githubusercontent.com/13470043/69144978-89098300-0b07-11ea-9dd5-f53f27e90f0e.png">

请问一下这个title要怎么加才显示？我设置了message的apnsContent和apnsPayload似乎都无效，谢谢

**Comment by ElfSundae** [comment]
apnsPayload 里设置 `title`

**Comment by sevenuncler** [comment]
> @ElfSundae
> <img alt="屏幕快照 2019-11-19 下午7 58 41" width="513" src="https://user-images.githubusercontent.com/13470043/69144977-8870ec80-0b07-11ea-8190-74d584ebc7d0.png">
> <img alt="屏幕快照 2019-11-19 下午7 59 26" width="505" src="https://user-images.githubusercontent.com/13470043/69144978-89098300-0b07-11ea-9dd5-f53f27e90f0e.png">
> 
> 请问一下这个title要怎么加才显示？我设置了message的apnsContent和apnsPayload似乎都无效，谢谢

{
    "key1": "value1",
    "apsField": {
        "mutable-content": 1,
        "sound": "abc.wav",
        "alert": {
            "title": "推送标题",
            "body": "推送内容"
        },
        "key2": "value2"
    }
}

https://faq.yunxin.163.com/kb/main/#/item/KB0198 apnsPayload可以参考下这里

**Comment by walkmanaly** [comment]
> > @ElfSundae
> > <img alt="屏幕快照 2019-11-19 下午7 58 41" width="513" src="https://user-images.githubusercontent.com/13470043/69144977-8870ec80-0b07-11ea-8190-74d584ebc7d0.png">
> > <img alt="屏幕快照 2019-11-19 下午7 59 26" width="505" src="https://user-images.githubusercontent.com/13470043/69144978-89098300-0b07-11ea-9dd5-f53f27e90f0e.png">
> > 请问一下这个title要怎么加才显示？我设置了message的apnsContent和apnsPayload似乎都无效，谢谢
> 
> {
> "key1": "value1",
> "apsField": {
> "mutable-content": 1,
> "sound": "abc.wav",
> "alert": {
> "title": "推送标题",
> "body": "推送内容"
> },
> "key2": "value2"
> }
> }
> 
> https://faq.yunxin.163.com/kb/main/#/item/KB0198 apnsPayload可以参考下这里

这个可以了，谢谢

**Comment by walkmanaly** [comment]
> > > @ElfSundae
> > > <img alt="屏幕快照 2019-11-19 下午7 58 41" width="513" src="https://user-images.githubusercontent.com/13470043/69144977-8870ec80-0b07-11ea-8190-74d584ebc7d0.png">
> > > <img alt="屏幕快照 2019-11-19 下午7 59 26" width="505" src="https://user-images.githubusercontent.com/13470043/69144978-89098300-0b07-11ea-9dd5-f53f27e90f0e.png">
> > > 请问一下这个title要怎么加才显示？我设置了message的apnsContent和apnsPayload似乎都无效，谢谢
> > 
> > 
> > {
> > "key1": "value1",
> > "apsField": {
> > "mutable-content": 1,
> > "sound": "abc.wav",
> > "alert": {
> > "title": "推送标题",
> > "body": "推送内容"
> > },
> > "key2": "value2"
> > }
> > }
> > https://faq.yunxin.163.com/kb/main/#/item/KB0198 apnsPayload可以参考下这里
> 
> 这个可以了，谢谢

用了这个链接的方案，安卓收不到推送了。请问一下怎么处理
