### ISSUE TITLE
部分表情包缺失

### ISSUE THREAD

**Issue by davieds** [netease-kit/nim-uikit-ios#251]
### 问题检查清单

感谢您向我们提出问题，在提交问题之前，请确认以下事宜：

- [x] 我已经阅读了组件文档: 

     [《项目结构介绍》](./Documents/nim_arch.md)

     [《界面排版自定义》](./Documents/nim_custom_ui.md)

     [《新消息类型集成》](./Documents/nim_custom_message.md)

     [《用户信息自定义》](./Documents/nim_userinfo.md)

     [《机器人消息排版指南》](./Documents/nim_robot.md)

- [x] 我已经阅读了[常见问题](http://dev.netease.im/docs/product/%E9%80%9A%E7%94%A8/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98?#iOS%E7%89%88SDK), 但是找不到相关解决方案。

- [x] 我已经阅读了[SDK 文档](http://dev.netease.im/docs/product/IM%E5%8D%B3%E6%97%B6%E9%80%9A%E8%AE%AF/SDK%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90/iOS%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90/%E6%A6%82%E8%A6%81%E4%BB%8B%E7%BB%8D), 但是找不到相关解决方案。
     
- [x] 我已经搜索了[当前问题](https://github.com/netease-im/NIM_iOS_UIKit/issues?utf8=✓&q=is%3Aissue), 但是找不到相关解决方案。

#### 问题现象

[描述具体问题表现]

#### 是否重现

[重现此问题的步骤]

#### 其它备注

[在这里添加任何其他相关细节]

pod 最新版本2.12.10

![image](https://user-images.githubusercontent.com/6236937/70965449-aad83480-20ca-11ea-914b-7f29bf670d8b.png)

**Comment by ElfSundae** [comment]
https://github.com/netease-im/NIM_iOS_UIKit/issues/243

**Comment by tsaievan** [comment]
你代码是不是没提交啊?? 你这个问题还是没解决啊, 兄弟

**Comment by ElfSundae** [comment]
@tsaievan 代码提交到 #227 PR 了，没被合并。
目前可以下载我的 [fork](https://github.com/ElfSundae/NIM_iOS_UIKit) 版本修复此问题，在你 Podfile 中 `pod 'NIMKit'`后加个 `source`:
```ruby
pod 'NIMKit', :source => 'https://github.com/ElfSundae/CocoaPods-Specs.git'
```
然后执行 `pod update`

**Comment by tsaievan** [comment]
完美解决, 谢谢

**Comment by eric1202** [comment]
> @tsaievan 代码提交到 #227 PR 了，没被合并。
> 目前可以下载我的 [fork](https://github.com/ElfSundae/NIM_iOS_UIKit) 版本修复此问题，在你 Podfile 中 `pod 'NIMKit'`后加个 `source`:
> 
> ```ruby
> pod 'NIMKit', :source => 'https://github.com/ElfSundae/CocoaPods-Specs.git'
> ```
> 
> 然后执行 `pod update`

安卓那边显示不了 这种类型 他们没有图库。。。
能改成那种通用的吗 第三方键盘输入那种

**Comment by ElfSundae** [comment]
@eric1202 Android 有啊 https://github.com/netease-im/NIM_Android_UIKit/blob/master/assets/emoji/emoji.xml
