### ISSUE TITLE
进入NIMSessionViewController页面，消息列表会从上刷到下面去

### ISSUE THREAD

**Issue by RomitLee** [netease-kit/nim-uikit-ios#268]
### 问题检查清单

感谢您向我们提出问题，在提交问题之前，请确认以下事宜：

- [x] 我已经阅读了组件文档: 

     [《项目结构介绍》](./Documents/nim_arch.md)

     [《界面排版自定义》](./Documents/nim_custom_ui.md)

     [《新消息类型集成》](./Documents/nim_custom_message.md)

     [《用户信息自定义》](./Documents/nim_userinfo.md)

     [《机器人消息排版指南》](./Documents/nim_robot.md)

- [x] 我已经阅读了[常见问题](http://dev.netease.im/docs/product/%E9%80%9A%E7%94%A8/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98?#iOS%E7%89%88SDK), 但是找不到相关解决方案。

- [x] 我已经阅读了[SDK 文档](http://dev.netease.im/docs/product/IM%E5%8D%B3%E6%97%B6%E9%80%9A%E8%AE%AF/SDK%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90/iOS%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90/%E6%A6%82%E8%A6%81%E4%BB%8B%E7%BB%8D), 但是找不到相关解决方案。
     
- [x] 我已经搜索了[当前问题](https://github.com/netease-im/NIM_iOS_UIKit/issues?utf8=✓&q=is%3Aissue), 但是找不到相关解决方案。

### 问题描述
进入NIMSessionViewController页面，消息列表会从上刷到下面去，而2.12.17就不会这样

#### 问题现象

进入NIMSessionViewController页面，消息列表会从上刷到下面去，而2.12.17就不会这样，下载了2.12.18的demo后，也是同样，怎样解决进入NIMSessionViewController直接就显示最新的消息，而不是有动画效果从上刷到下

#### 是否重现

必现

**Comment by byljbdh** [comment]
修改这个方法
- (void)autoFetchMessages
{
    if (![self.sessionConfig respondsToSelector:@selector(autoFetchWhenOpenSession)]
        || self.sessionConfig.autoFetchWhenOpenSession) {
        __weak typeof(self) weakSelf = self;
        dispatch_group_t group = dispatch_group_create();
        
        dispatch_group_enter(group);
        [self.dataSource enhancedResetMessages:^(NSError *error, NSArray *models) {
            [self refreshAllAfterFetchCommentsByModels:models];
            if([weakSelf.delegate respondsToSelector:@selector(didFetchMessageData)])
            {
                [weakSelf.delegate didFetchMessageData];
                
                if (![self.sessionConfig respondsToSelector:@selector(autoFetchAttachment)]
                    || self.sessionConfig.autoFetchAttachment) {
                    [weakSelf.dataSource checkAttachmentState:weakSelf.items];
                }
            }
            dispatch_group_leave(group);
        }];
        
        dispatch_group_notify(group, dispatch_get_main_queue(), ^{
            [self loadMessagePins:^(NSError *error) {
            }];
        });
    }
}
