### ISSUE TITLE
Crash: -[NTESSessionConfig emotionItems]: unrecognized selector

### ISSUE THREAD

**Issue by ElfSundae** [netease-kit/nim-uikit-ios#270]
NIMKit 2.12.18
https://github.com/netease-im/NIM_iOS_UIKit/blob/68b4c11dd0be5e91988d1ac5e54b78bedd0e7331/NIMKit/NIMKit/Classes/Sections/Session/ViewController/NIMSessionViewController.m#L988

`sessionConfig` 没有实现 `-emotionItems` 导致 crash.

**Comment by walkmanaly** [comment]
> NIMKit 2.12.18
> https://github.com/netease-im/NIM_iOS_UIKit/blob/68b4c11dd0be5e91988d1ac5e54b78bedd0e7331/NIMKit/NIMKit/Classes/Sections/Session/ViewController/NIMSessionViewController.m#L988
> 
> `sessionConfig` 没有实现 `-emotionItems` 导致 crash.

请问一下 配置贴图表情使用- (NSArray<NIMInputEmoticonCatalog *> *)charlets时，要把表情放到NIMKitEmoticon.bundle里面，这样会改动SDK了。有没有什么好点的办法？

**Comment by ElfSundae** [comment]
NIMKitEmoticon.bundle 里放的是 NIMKit 内置的 Emoji 表情，不是贴图。
贴图 charlets 随便放哪都行，实现 `- (NSArray<NIMInputEmoticonCatalog *> *)charlets` 这个方法，返回对象数组即可。可以参考 Demo 写法。

**Comment by walkmanaly** [comment]
@ElfSundae 请问一下怎么修改NIMMessageCell的高度呀，ths

**Comment by ElfSundae** [comment]
demo 里搜 `NIMSessionContentConfig` ，这个配置每种消息的 contentView 宽高、cell 边距。

**Comment by walkmanaly** [comment]
我的自定义消息cell是按这个配置的，但是cell的高度找不到API呢

**Comment by ElfSundae** [comment]
cell的高度是根据这个计算的啊，cell 高度等于 content 高度+上下边距。NIMSessionTableAdapter.m

**Comment by walkmanaly** [comment]
@ElfSundae 
- (CGSize)contentSize:(NIMMessageModel *)model cellWidth:(CGFloat)width {
    if ([self canLayout:model]) {
        NIMCustomObject *object = model.message.messageObject;
        NTESAttachment *attachment = object.attachment;
        
        if ([attachment.type integerValue] == 5) {
            return CGSizeMake(220, 66);
        } else if ([attachment.type integerValue] == 6) {
            NIMUser *send = [[NIMSDK sharedSDK].userManager userInfo:attachment.sendPacketId];
            NIMUser *recieve = [[NIMSDK sharedSDK].userManager userInfo:attachment.openPacketId];
            
            if (![send.userId isEqual:[CYLoignModel shareCYLogin].userModel.yx_accid]) {
                if (![recieve.userId isEqualToString:[CYLoignModel shareCYLogin].userModel.yx_accid]) {
                    return CGSizeZero;
                }
            }
            
            return CGSizeMake(kScreenWidth, 5);
        } else if ([attachment.type integerValue] == 3) {
            return CGSizeMake(100, 100);
        }
    }
    return [super contentSize:model cellWidth:width];
}
我返回CGSizeZero，还是有个高度为50的空白cell。
