### ISSUE TITLE
NIMKitDependency 里适配一下Toast

### ISSUE THREAD

**Issue by ClegeJJ** [netease-kit/nim-uikit-ios#276]
![image](https://user-images.githubusercontent.com/13790283/83706642-983ac300-a64a-11ea-91cc-59f6c438c6a7.png)

#if __has_include(<Toast/UIView+Toast.h>)
#import <Toast/UIView+Toast.h>
#elif __has_include("UIView+Toast.h")
#import "Toast/UIView+Toast.h"
#else
@import Toast;
#endif

只需要改成这样就行了 我发现<Toast/Toast.h>早就没了

**Comment by ElfSundae** [comment]
这个要看你怎么集成了，Framework 方式集成 Toast 的话，头文件是 [`<Toast/Toast.h>`](https://github.com/scalessec/Toast/blob/master/Toast-Framework/Toast.h)
