### ISSUE TITLE
pod 与YYKit同时集成报WebP.framework冲突

### ISSUE THREAD

**Issue by yanashenyang** [netease-kit/nim-uikit-ios#279]
### 问题检查清单

感谢您向我们提出问题，在提交问题之前，请确认以下事宜：

- [x] 我已经阅读了组件文档: 

     [《项目结构介绍》](./Documents/nim_arch.md)

     [《界面排版自定义》](./Documents/nim_custom_ui.md)

     [《新消息类型集成》](./Documents/nim_custom_message.md)

     [《用户信息自定义》](./Documents/nim_userinfo.md)

     [《机器人消息排版指南》](./Documents/nim_robot.md)

- [x] 我已经阅读了[常见问题](http://dev.netease.im/docs/product/%E9%80%9A%E7%94%A8/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98?#iOS%E7%89%88SDK), 但是找不到相关解决方案。

- [x] 我已经阅读了[SDK 文档](http://dev.netease.im/docs/product/IM%E5%8D%B3%E6%97%B6%E9%80%9A%E8%AE%AF/SDK%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90/iOS%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90/%E6%A6%82%E8%A6%81%E4%BB%8B%E7%BB%8D), 但是找不到相关解决方案。
     
- [x] 我已经搜索了[当前问题](https://github.com/netease-im/NIM_iOS_UIKit/issues?utf8=✓&q=is%3Aissue), 但是找不到相关解决方案。

### 问题描述
集成
pod 'NIMKit/Full' #IM 音视频完整版po
pod 'SSZipArchive' #IM 云信需要
pod 'FMDB' #IM 云信需要
的时候，
 
项目中集成了 YYKit ，pod报冲突，搞了三天都没解决
[!] The 'Pods-WisdomCraftsman' target has frameworks with conflicting names: webp.framework.
#### 问题现象

Update all pods
Updating local specs repositories
Analyzing dependencies
Pre-downloading: `Masonry` from `https://github.com/pingwinator/Masonry.git`
Downloading dependencies
Installing FLAnimatedImage (1.0.12)
Installing M80AttributedLabel (1.9.9)
Installing Masonry 1.1.1
Installing NIMKit (2.12.22)
Installing NIMSDK (7.7.4)
Installing SDWebImage 5.0.6 (was 5.8.3 and source changed to `https://cdn.cocoapods.org/` from `trunk`)
Installing Toast (3.1.0)
Installing YYImage (1.0.4)
[!] The 'Pods-WisdomCraftsman' target has frameworks with conflicting names: webp.framework.

#### 是否重现

[!] The 'Pods-WisdomCraftsman' target has frameworks with conflicting names: webp.framework.

#### 其它备注

[!] The 'Pods-WisdomCraftsman' target has frameworks with conflicting names: webp.framework.

[在这里添加任何其他相关细节]

**Comment by ElfSundae** [comment]
YYKit 和 YYImage 都包含了 webp.framework

**Comment by ElfSundae** [comment]
YYKit 已经分成组件了，项目里集成各组件，不要直接集成 YYKit

**Comment by WenchaoD** [comment]
暂时解决办法如下：
1. Podfile中只保留YYKit，执行pod install
2. 在Pods目录下，找到YYImage/Vendor/WebP.framework，删除
3. Podfile中重新添加NIMKit，重新pod update

**Comment by ElfSundae** [comment]
可以添加个 pre_install hook 自动删除多余的 WebP.framework
这个问题是 YYKit 和 YYImage 是两个互相冲突的组件，两者都包含了 WebP.framework。可以试试以下解决方案：
1. YYKit 已经拆分成多个独立组件了，可以根据项目需要引入独立的组件，比如 YYImage, YYText 等，不要使用 YYKit。（我没用过 YY 系列的组件，不知道 YYKit 和 独立组件的代码一样不，所以不晓得迁移成本有多大）
2. 修改 YYKit，移除 WebP.framework 引入 libwebp 依赖，然后发布 YYText 到私有 CocoaPods 源。
3. 修改 YYImage，移除 WebP.framework 引入 libwebp 依赖，然后发布 YYText 到私有 CocoaPods 源。这个我之前做过，可以参考 https://github.com/ElfSundae/YYImage
4. 在 `Podfile` 中指定 YYImage 从我的私有源（不包含 WebP.framework）安装：（未尝试）
    ```
    pod 'YYImage', :source => 'https://github.com/ElfSundae/CocoaPods-Specs.git'
    ```
