### ISSUE TITLE
pod 集成 与 百度地图冲突

### ISSUE THREAD

**Issue by yanashenyang** [netease-kit/nim-uikit-ios#280]
### 问题检查清单

感谢您向我们提出问题，在提交问题之前，请确认以下事宜：

- [ ] 我已经阅读了组件文档: 

     [《项目结构介绍》](./Documents/nim_arch.md)

     [《界面排版自定义》](./Documents/nim_custom_ui.md)

     [《新消息类型集成》](./Documents/nim_custom_message.md)

     [《用户信息自定义》](./Documents/nim_userinfo.md)

     [《机器人消息排版指南》](./Documents/nim_robot.md)

- [ ] 我已经阅读了[常见问题](http://dev.netease.im/docs/product/%E9%80%9A%E7%94%A8/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98?#iOS%E7%89%88SDK), 但是找不到相关解决方案。

- [ ] 我已经阅读了[SDK 文档](http://dev.netease.im/docs/product/IM%E5%8D%B3%E6%97%B6%E9%80%9A%E8%AE%AF/SDK%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90/iOS%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90/%E6%A6%82%E8%A6%81%E4%BB%8B%E7%BB%8D), 但是找不到相关解决方案。
     
- [ ] 我已经搜索了[当前问题](https://github.com/netease-im/NIM_iOS_UIKit/issues?utf8=✓&q=is%3Aissue), 但是找不到相关解决方案。

### 问题描述
pod 集成 与 百度地图冲突
#### 问题现象

Analyzing dependencies
Downloading dependencies
Installing M80AttributedLabel (1.9.9)
Installing NIMKit (1.8.0)
Installing NIMSDK (4.1.0)
Installing Toast (4.0.0)

[!] The 'Pods-WisdomCraftsman' target has libraries with conflicting names: libcrypto.a and libssl.a.
[描述具体问题表现]
百度地图 BaiduMapKit 中有  libcrypto.a and libssl.a.
pod报如下冲突
[!] The 'Pods-WisdomCraftsman' target has libraries with conflicting names: libcrypto.a and libssl.a.

[重现此问题的步骤]

#### 其它备注

[在这里添加任何其他相关细节]

**Comment by HarryWang0909** [comment]
我也遇到了这个问题, 我把百度地图的libcrypto.a and libssl.a.依旧报错, 接网易云信接的白头发都多了几根

**Comment by zhangyunfeiFly** [comment]
同问 有解决的小伙伴么？

**Comment by zhangyunfeiFly** [comment]
<img width="598" alt="截屏2021-03-11 上午10 32 51" src="https://user-images.githubusercontent.com/20281212/110726969-5aac3b80-8255-11eb-8560-caade5aa3e3a.png">
