### ISSUE TITLE
pod 集成时报错

### ISSUE THREAD

**Issue by yanashenyang** [netease-kit/nim-uikit-ios#281]
### 问题检查清单

感谢您向我们提出问题，在提交问题之前，请确认以下事宜：

- [ ] 我已经阅读了组件文档: 

     [《项目结构介绍》](./Documents/nim_arch.md)

     [《界面排版自定义》](./Documents/nim_custom_ui.md)

     [《新消息类型集成》](./Documents/nim_custom_message.md)

     [《用户信息自定义》](./Documents/nim_userinfo.md)

     [《机器人消息排版指南》](./Documents/nim_robot.md)

- [ ] 我已经阅读了[常见问题](http://dev.netease.im/docs/product/%E9%80%9A%E7%94%A8/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98?#iOS%E7%89%88SDK), 但是找不到相关解决方案。

- [ ] 我已经阅读了[SDK 文档](http://dev.netease.im/docs/product/IM%E5%8D%B3%E6%97%B6%E9%80%9A%E8%AE%AF/SDK%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90/iOS%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90/%E6%A6%82%E8%A6%81%E4%BB%8B%E7%BB%8D), 但是找不到相关解决方案。
     
- [ ] 我已经搜索了[当前问题](https://github.com/netease-im/NIM_iOS_UIKit/issues?utf8=✓&q=is%3Aissue), 但是找不到相关解决方案。

### 问题描述
pod 集成时报错

 pod 'NIMKit/Full' #IM 音视频完整版po
    pod 'SSZipArchive' #IM 云信需要
    pod 'FMDB' #IM 云信需要

#### 问题现象

[!] The 'Pods-WisdomCraftsman' target has transitive dependencies that include statically linked binaries: (/Users/yana/Documents/WisdomCraftsmanIOS/Pods/NIMSDK/NIMAVChat/Libs/libGPUImage.a, /Users/yana/Documents/WisdomCraftsmanIOS/Pods/NIMSDK/NIMAVChat/Libs/libnio.a, /Users/yana/Documents/WisdomCraftsmanIOS/Pods/NIMSDK/NIMAVChat/Libs/libNMCVideoModule.a, /Users/yana/Documents/WisdomCraftsmanIOS/Pods/NIMSDK/NIMAVChat/Libs/libnts.a, /Users/yana/Documents/WisdomCraftsmanIOS/Pods/NIMSDK/NIMAVChat/Libs/libnvs.a, /Users/yana/Documents/WisdomCraftsmanIOS/Pods/NIMSDK/NIMAVChat/Libs/libopenh264.a, /Users/yana/Documents/WisdomCraftsmanIOS/Pods/NIMSDK/NIMAVChat/Libs/libopus.a, /Users/yana/Documents/WisdomCraftsmanIOS/Pods/NIMSDK/NIMSDK/Libs/libaacplus.a, /Users/yana/Documents/WisdomCraftsmanIOS/Pods/NIMSDK/NIMSDK/Libs/libcrypto.a, /Users/yana/Documents/WisdomCraftsmanIOS/Pods/NIMSDK/NIMSDK/Libs/libevent.a, /Users/yana/Documents/WisdomCraftsmanIOS/Pods/NIMSDK/NIMSDK/Libs/libssl.a, /Users/yana/Documents/WisdomCraftsmanIOS/Pods/NIMSDK/NIMSDK/NIMSDK.framework, and /Users/yana/Documents/WisdomCraftsmanIOS/Pods/NIMSDK/NIMAVChat/NIMAVChat.framework)

#### 是否重现

[重现此问题的步骤]

#### 其它备注

[在这里添加任何其他相关细节]

**Comment by ElfSundae** [comment]
pod 版本更新下

**Comment by coderDeviCheng** [comment]
我是最新版的pod 也遇到这个问题了，请问怎么搞

**Comment by ElfSundae** [comment]
报什么错？

**Comment by HarryWang0909** [comment]
target has transitive dependencies that include statically linked binaries,  我也遇到这个问题了,

**Comment by ElfSundae** [comment]
最新版的 pod (1.10.0) 应该不会报这个错... 如果确实是最新版的 pod 报错，把下面的粘贴进 `Podfile` 中再执行 `pod update`
```ruby
# https://github.com/CocoaPods/CocoaPods/issues/3289#issuecomment-84005488
pre_install do |installer|
    internalInstaller = installer.installer
    def internalInstaller.verify_no_static_framework_transitive_dependencies; end
end
```

**Comment by HarryWang0909** [comment]
> 最新版的 pod (1.10.0) 应该不会报这个错... 如果确实是最新版的 pod 报错，把下面的粘贴进 `Podfile` 中再执行 `pod update`
> 
> ```ruby
> # https://github.com/CocoaPods/CocoaPods/issues/3289#issuecomment-84005488
> pre_install do |installer|
>     internalInstaller = installer.installer
>     def internalInstaller.verify_no_static_framework_transitive_dependencies; end
> end
> ```

我的pod版本是1.10的,我按照你的回复,将上面的粘贴到podfile, 还是报错
![Snip20201209_27](https://user-images.githubusercontent.com/20148501/101550279-fb3a5780-39e9-11eb-84e3-2f34a981ed55.png)
![Snip20201209_28](https://user-images.githubusercontent.com/20148501/101550304-04c3bf80-39ea-11eb-8fb2-285ddc608645.png)



报错信息如下: 
[!] An error occurred while processing the pre-install hook of the Podfile.

undefined method `installer' for #<Pod::Installer:0x00007fa1fc636398>
Did you mean?  install!

/Users/wanghui/Documents/直播/zhibo/Podfile:8:in `block (2 levels) in from_ruby'
/Users/wanghui/.rvm/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/podfile.rb:162:in `pre_install!'
/Users/wanghui/.rvm/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:869:in `run_podfile_pre_install_hook'
/Users/wanghui/.rvm/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:857:in `block in run_podfile_pre_install_hooks'
/Users/wanghui/.rvm/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:145:in `message'
/Users/wanghui/.rvm/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:856:in `run_podfile_pre_install_hooks'
/Users/wanghui/.rvm/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:254:in `block in download_dependencies'
/Users/wanghui/.rvm/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:64:in `section'
/Users/wanghui/.rvm/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:252:in `download_dependencies'
/Users/wanghui/.rvm/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:161:in `install!'
/Users/wanghui/.rvm/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.10.0/lib/cocoapods/command/update.rb:63:in `run'
/Users/wanghui/.rvm/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/wanghui/.rvm/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.10.0/lib/cocoapods/command.rb:52:in `run'
/Users/wanghui/.rvm/gems/ruby-2.5.3@global/gems/cocoapods-1.10.0/bin/pod:55:in `<top (required)>'
/Users/wanghui/.rvm/rubies/ruby-2.5.3/bin/pod:23:in `load'
/Users/wanghui/.rvm/rubies/ruby-2.5.3/bin/pod:23:in `<main>'

**Comment by HarryWang0909** [comment]
> 最新版的 pod (1.10.0) 应该不会报这个错... 如果确实是最新版的 pod 报错，把下面的粘贴进 `Podfile` 中再执行 `pod update`
> 
> ```ruby
> # https://github.com/CocoaPods/CocoaPods/issues/3289#issuecomment-84005488
> pre_install do |installer|
>     internalInstaller = installer.installer
>     def internalInstaller.verify_no_static_framework_transitive_dependencies; end
> end
> ```

根据你发的https://github.com/CocoaPods/CocoaPods/issues/3289#issuecomment-84005488 已找到解决方法: 
    pre_install do |installer|
        def installer.verify_no_static_framework_transitive_dependencies; end
    end

**Comment by ElfSundae** [comment]
哦，直接拷贝过来的，忘改了。新版的 installer 改了。

刚看了下我项目的 git 记录，我以前用的是：
```ruby
pre_install do |installer|
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end
```
如果方便的话，能不能在你那试下上面这个还有用吗？谢谢。 把你那三行先注释，拷贝我这三行，执行 pod update 看报错不。
