### ISSUE TITLE
NIMAvatarImageView报错

### ISSUE THREAD

**Issue by ui03** [netease-kit/nim-uikit-ios#282]
NIMAvatarImageView报错
No visible @interface for 'NIMAvatarImageView' declares the selector 'sd_showActivityIndicatorView'
No visible @interface for 'NIMAvatarImageView' declares the selector 'sd_addActivityIndicator'

No visible @interface for 'NIMAvatarImageView' declares the selector 'sd_removeActivityIndicator'

**Comment by 1224860397** [comment]
我也遇到了，请问解决了吗

**Comment by tanlianghao** [comment]
同样遇到了，请问有解决办法吗

**Comment by lzs942737012** [comment]
同样遇到了，请问有解决办法吗

**Comment by ElfSundae** [comment]
pod集成的还是手动集成？SDWebImage的版本不对？NIMKit依赖SDWebImage 5.x

**Comment by lzs942737012** [comment]
这边是pod集成的 pod里面的SDWebImage是没有写版本号 直接更新整个NIMKit/Full 库的  然后将pod里面自己加的SDWebImage删除了 重新更新也是不行

**Comment by ElfSundae** [comment]
你看下 Podfile.lock 文件中的 SDWebImage 是什么版本。有可能别的库依赖了老的 SDWebImage

**Comment by ElfSundae** [comment]
你们说的是同一个问题么？NIMAvatarImageView 的 sd_showActivityIndicatorView 等方法已经在 NIMKit 2.12.0 里移除了，同时将  SDWebImage 从 4.x 升级到 5.x 了。
https://github.com/netease-im/NIM_iOS_UIKit/commit/966467641590d349a38c5cea7c2a03dd831418dc#diff-431974b08c33c0c66b0169351e519f710284d986ec796cca7d5c6ff276cc2701L195-L197

楼主的报错貌似是集成了老版本的 NIMKit （低于 2.12.0） 和 5.x 的 SDWebImage
