### ISSUE TITLE
Pod 依赖库能不能不要写死版本？

### ISSUE THREAD

**Issue by luoyuant** [netease-kit/nim-uikit-ios#283]
你们的pod依赖都写死了，例如：NIMKit/Core依赖SDWebImage(5.0.6)，Toast (3.0)；
这就导致已经安装了SDWebImage和Toast老是报错，要把这两个写死版本才行，而且不能更新这些依赖。

你们写依赖>=某个版本就行了啊！

**Comment by ElfSundae** [comment]
有对应的没指定版本号的 pod ： `NIMKit/Full_Free`, `NIMKit/Lite_Free`
https://github.com/netease-im/NIM_iOS_UIKit/blob/master/NIMKit.podspec

**Comment by luoyuant** [comment]
@ElfSundae 还是不行。我还装了你们的七鱼QY_iOS_SDK，它指定了NIMSDK_LITE(7.6.0)，但是NIMKit/Lite_Free又指定NIMSDK_LITE(7.7.4)

**Comment by ElfSundae** [comment]
我不是网易官方人员。
QY_iOS_SDK 我没用过，看它的 podspec 没指定 NIMSDK 啊 https://github.com/qiyukf/QIYU_iOS_SDK/blob/master/QIYU_iOS_SDK.podspec

如果有多个库依赖不同版本的某库，可以在你 app 的 Podfile 中强制指定（覆盖）某库的版本（印象中是这样，你可以试试）。
