### ISSUE TITLE
 Error installing YYImage

### ISSUE THREAD

**Issue by coderDeviCheng** [netease-kit/nim-uikit-ios#286]
### 问题检查清单

感谢您向我们提出问题，在提交问题之前，请确认以下事宜：

- [ ] 我已经阅读了组件文档: 

     [《项目结构介绍》](./Documents/nim_arch.md)

     [《界面排版自定义》](./Documents/nim_custom_ui.md)

     [《新消息类型集成》](./Documents/nim_custom_message.md)

     [《用户信息自定义》](./Documents/nim_userinfo.md)

     [《机器人消息排版指南》](./Documents/nim_robot.md)

- [ ] 我已经阅读了[常见问题](http://dev.netease.im/docs/product/%E9%80%9A%E7%94%A8/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98?#iOS%E7%89%88SDK), 但是找不到相关解决方案。

- [ ] 我已经阅读了[SDK 文档](http://dev.netease.im/docs/product/IM%E5%8D%B3%E6%97%B6%E9%80%9A%E8%AE%AF/SDK%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90/iOS%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90/%E6%A6%82%E8%A6%81%E4%BB%8B%E7%BB%8D), 但是找不到相关解决方案。
     
- [ ] 我已经搜索了[当前问题](https://github.com/netease-im/NIM_iOS_UIKit/issues?utf8=✓&q=is%3Aissue), 但是找不到相关解决方案。

#### 问题现象

[描述具体问题表现]

#### 是否重现

[重现此问题的步骤]

#### 其它备注

  pod 'NIMKit/Lite', '~> 2.13.6' 
换了trunk源 清华源等好几个源，开了vpn  谷歌百度的方法基本都试过了 都一直卡在这一步
![231598324329_ pic_hd](https://user-images.githubusercontent.com/34669007/91120003-375ddc80-e6c7-11ea-8c72-5930258e99a9.jpg)
不知道怎么办了,是在不行只有手动集成了

**Comment by ElfSundae** [comment]
不是源的问题，是你命令行没翻出去，github下载慢。解决办法：开代理，设置命令行的 http_proxy 或者修改 git 的配置给 github.com 加个代理。

**Comment by coderDeviCheng** [comment]
我设置了代理 git config --global http.proxy 或者git config --global http.proxy localhost:51525或者 git config --global http.proxy http:172.16.13.171:8080 都不行，还是同样卡在yyimage

**Comment by ElfSundae** [comment]
代理地址是 `协议://host:port` 你这几种写法都不对。
命令行全局翻：命令行里执行 `export http_proxy=http://127.0.0.1:1087; export https_proxy=http://127.0.0.1:1087` 然后可以执行 `curl https://www.google.com` 测试能访问 Google 不，不能访问说明你的 HTTP 代理连不上或者不能翻。
或者 git 全局翻 `git config --global http.proxy 'socks5://127.0.0.1:1080'` 这里支持 HTTP 代理和 Socks 代理。
或者 git 指定翻某域名；或者配置 sshconfig 翻 git:// ssh:// 协议 ；或者 privoxy 自动代理；等等，具体问 Google.

实在搞不定了可以试试从我的私有源下载：在 `Podfile` 中添加以下行：
```
pod 'YYImage', :source => 'https://github.com/ElfSundae/CocoaPods-Specs.git'
```
然后执行 `pod update`

**Comment by coderDeviCheng** [comment]
我用你说的方法还是不行  奇怪的是我pod search 能正常搜到  但是当更新项目文件的时就报这个错（试了很多百度的方法，导致本来正常更新的库都没法更新了，现在所有库都更新不起）
![58451B21-327E-4C72-8889-B3FC62229680](https://user-images.githubusercontent.com/34669007/91607908-3e2a6f00-e9a7-11ea-9efe-fd3f4cbc75db.png)

**Comment by ElfSundae** [comment]
代理地址不对，代理是要你本机电脑先翻墙再开http代理，不是随便填个地址就行了。看你的错误信息貌似你把pod源搞坏了，执行pod repo查看下现在有什么源，看下Podfile中有没有定义source

**Comment by coderDeviCheng** [comment]
3个源 trunk  清华源 码云源  都是同样的结果 127.0.0.1 port 1080: Connection refused 我手动删除了repo里面清华和 码云源 podfile里有source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'和#source 'https://gitee.com/mirrors/CocoaPods-Specs'  这2个源 我注释了其中一个

**Comment by coderDeviCheng** [comment]
大佬 要不你加我qq 562117804 这么沟通效率太低了

**Comment by jhfkf** [comment]
SDImage不能用吗 为啥要价格YYImage

**Comment by jhfkf** [comment]
同样的问题 SDImage不能用吗 为啥要额外加一个YYImage？
