### ISSUE TITLE
发送自定义卡片消息的时候，老是出现重发的提示，实际上已经发送成功了，已升级最新版本3.0.0

### ISSUE THREAD

**Issue by huasong5870977** [netease-kit/nim-uikit-ios#292]
![Lark20201020-173921](https://user-images.githubusercontent.com/33717457/96569047-3c23c300-12fb-11eb-83a0-5005ca387e07.jpeg)

**Comment by grassInSpring** [comment]
- (void)sendMessage:(NIMMessage *)message  didCompleteWithError:(nullable NSError *)error; 
- 这里刷新一下refreshMessages
