### ISSUE TITLE
代码过于老旧(如果选型纠结中，可以对比下其他家)

### ISSUE THREAD

**Issue by include11** [netease-kit/nim-uikit-ios#311]
### 问题检查清单

感谢您向我们提出问题，在提交问题之前，请确认以下事宜：

- [x] 我已经阅读了组件文档: 

     [《项目结构介绍》](./Documents/nim_arch.md)

     [《界面排版自定义》](./Documents/nim_custom_ui.md)

     [《新消息类型集成》](./Documents/nim_custom_message.md)

     [《用户信息自定义》](./Documents/nim_userinfo.md)

     [《机器人消息排版指南》](./Documents/nim_robot.md)

- [x] 我已经阅读了[常见问题](http://dev.netease.im/docs/product/%E9%80%9A%E7%94%A8/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98?#iOS%E7%89%88SDK), 但是找不到相关解决方案。

- [x] 我已经阅读了[SDK 文档](http://dev.netease.im/docs/product/IM%E5%8D%B3%E6%97%B6%E9%80%9A%E8%AE%AF/SDK%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90/iOS%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90/%E6%A6%82%E8%A6%81%E4%BB%8B%E7%BB%8D), 但是找不到相关解决方案。
     
- [x] 我已经搜索了[当前问题](https://github.com/netease-im/NIM_iOS_UIKit/issues?utf8=✓&q=is%3Aissue), 但是找不到相关解决方案。

### 问题描述

1.Demo里面还在用UIAlert等被苹果废弃的代码

2.Demo依赖的第三方库，都是依赖第三方的很古老的代码，比如SDWebImage等。如果将这个Demo用于开发，会有依赖冲突

3.这套Demo应该是好几年前写的，平常更新也只是针对网易的功能例行更新，其他代码基本没动。

4.如果是IM类的软件，在会话界面需有向上滚动查看未读消息和向下滚动查看最新消息，这些功能Demo也没有。

**Comment by ElfSundae** [comment]
> 对比下其他家

比如哪家？
