### ISSUE TITLE
引入sdk报错

### ISSUE THREAD

**Issue by YunzzzZ** [netease-kit/nim-uikit-ios#327]
Could not find module 'NEKitCore' for target 'x86_64-apple-ios-simulator'; found: armv7-apple-ios, arm64-apple-ios, at: /Users/jidu/Desktop/work/chengyou/Pods/NECoreKit/NEKitCore.framework/Modules/NEKitCore.swiftmodule

**Comment by maghzchenyu** [comment]
将在下个版本修复xcode13.3+上模拟器无法运行问题(预计2022.5.19日发布)

**Comment by shine2008** [comment]
已在版本9.0.1修复
