### ISSUE TITLE
netWorkReachability方法崩溃

### ISSUE THREAD

**Issue by zungjam** [netease-kit/nim-uikit-ios#329]

**Comment by Dongshanxu** [comment]
> _No description provided._

具体崩溃在哪里？ 或者你描述一下 导致崩溃的操作

**Comment by Dongshanxu** [comment]
> _No description provided._

具体崩溃在哪里？ 或者你描述一下导致崩溃的操作？

**Comment by zungjam** [comment]
> > _No description provided._
> 
> 具体崩溃在哪里？ 或者你描述一下导致崩溃的操作？

只要跳转到使用了NEChatDetectNetworkTool.shareInstance.netWorkReachability()方法的页面都会崩溃
崩溃在Alamofire的Reachability()方法里，到源码里注释掉NEChatDetectNetworkTool.shareInstance.netWorkReachability()就正常了

**Comment by Dongshanxu** [comment]
> 

你的podfile引用发我看看

**Comment by Dongshanxu** [comment]
> 



> > > _No description provided._
> > 
> > 
> > 具体崩溃在哪里？ 或者你描述一下导致崩溃的操作？
> 
> 只要跳转到使用了NEChatDetectNetworkTool.shareInstance.netWorkReachability()方法的页面都会崩溃 崩溃在Alamofire的Reachability()方法里，到源码里注释掉NEChatDetectNetworkTool.shareInstance.netWorkReachability()就正常了


你的podfile引用发我看看

**Comment by Dongshanxu** [comment]
> > > _No description provided._
> > 
> > 
> > 具体崩溃在哪里？ 或者你描述一下导致崩溃的操作？
> 
> 只要跳转到使用了NEChatDetectNetworkTool.shareInstance.netWorkReachability()方法的页面都会崩溃 崩溃在Alamofire的Reachability()方法里，到源码里注释掉NEChatDetectNetworkTool.shareInstance.netWorkReachability()就正常了

Alamofire 新版本要求运行在ios 10以上系统，我们项目兼容ios 9+的系统所以使用 Alamofire的新版本会导致我们组件中使用的方法找不到导致崩溃，请开发者在你的项目中指定一下Alamofire的版本为 4.9.1 即可解决崩溃问题。
