### ISSUE TITLE
如何第一次进页面，就让tableView自动在底部呢？不想看到进去后还滚动到底部

### ISSUE THREAD

**Issue by paulAndKey** [netease-kit/nim-uikit-ios#335]
不想看到进去后还滚动到底部的动画，而且我取消了demo里的延迟和动画，但是聊天页面tableViewCell会出现闪动跳动。效果非常不好。

**Comment by Dongshanxu** [comment]
> 不想看到进去后还滚动到底部的动画，而且我取消了demo里的延迟和动画，但是聊天页面tableViewCell会出现闪动跳动。效果非常不好。

你使用的是“消息”的聊天页面，还是“圈组”

**Comment by paulAndKey** [comment]
> > 不想看到进去后还滚动到底部的动画，而且我取消了demo里的延迟和动画，但是聊天页面tableViewCell会出现闪动跳动。效果非常不好。
> 
> 你使用的是“消息”的聊天页面，还是“圈组”

NIMSessionViewController,消息的聊天页面

**Comment by Dongshanxu** [comment]
> NIMSessionViewController

您好，NIMSessionViewController是老的demo中的类，已经不维护了，请使用新版本的demo。目前开源的nim-uikit-ios 就是新的demo

**Comment by paulAndKey** [comment]
> > NIMSessionViewController
> 
> 您好，NIMSessionViewController是老的demo中的类，已经不维护了，请使用新版本的demo。目前开源的nim-uikit-ios 就是新的demo

看了下，新的是swift版本，因为项目要求的是OC，而且已经在此基础上做了一版，在不使用新的demo下，在NIMSessionViewController中如何能解决这个问题？谢谢了

**Comment by Dongshanxu** [comment]
> NIMSessionViewController

![image](https://user-images.githubusercontent.com/15043185/171352967-1e1df400-7906-4c57-8e8f-de626588f5ec.png)

**Comment by sclcoder** [comment]
我最近集成时也遇到类似的问题，因为云信的拉取回复消息时异步的，回调时很容易不在底部。我后来将tabeView、cell做了x轴镜像的方式处理的
