### ISSUE TITLE
关于接收的语音消息不能播放的问题attachmentDownloadState = NIMMessageAttachmentDownloadStateFailed

### ISSUE THREAD

**Issue by paulAndKey** [netease-kit/nim-uikit-ios#336]
能收到别人发过来的消息，但是不能播放，attachmentDownloadState = NIMMessageAttachmentDownloadStateFailed

**Comment by Dongshanxu** [comment]
> a

你是在哪里截取的这个错误？
是这两个哪一个？
/**
 *  开始录制音频的回调
 *
 *  @param filePath 录制的音频的文件路径
 *  @param error    错误信息
 *  @discussion 如果录音失败，filePath 有可能为 nil
 */
- (void)recordAudio:(nullable NSString *)filePath didBeganWithError:(nullable NSError *)error;

/**
 *  录制音频完成后的回调
 *
 *  @param filePath 录制完成的音频文件路径
 *  @param error    错误信息
 */
- (void)recordAudio:(nullable NSString *)filePath didCompletedWithError:(nullable NSError *)error;
