### ISSUE TITLE
Module compiled with Swift 5.6 cannot be imported by the Swift 5.7 compiler: xxx/Pods/NECoreIMKit/NEKitCoreIM.framework/Modules/NEKitCoreIM.swiftmodule/x86_64-apple-ios-simulator.swiftmodule

### ISSUE THREAD

**Issue by winddpan** [netease-kit/nim-uikit-ios#341]
Module compiled with Swift 5.6 cannot be imported by the Swift 5.7 compiler: xxx/Pods/NECoreIMKit/NEKitCoreIM.framework/Modules/NEKitCoreIM.swiftmodule/x86_64-apple-ios-simulator.swiftmodule

编译framework时可以使用：
BUILD_LIBRARY_FOR_DISTRIBUTION = YES;

**Comment by Dongshanxu** [comment]
> 

9.2.7及以后版本已解决
