### ISSUE TITLE
方法都是public不是open，没法使用。用回OC版本了。

### ISSUE THREAD

**Issue by winddpan** [netease-kit/nim-uikit-ios#342]
ConversationListViewController
ConversationtViewController

**Comment by guanJiaPo** [comment]
oc版本哪里找？

**Comment by sclcoder** [comment]
> 

3.7版本以及一下版本都是OC的

**Comment by Dongshanxu** [comment]
> ConversationListViewController ConversationtViewController

新版本都已支持

**Comment by Dongshanxu** [comment]
> oc版本哪里找？

联系技术支持
