### ISSUE TITLE
有oc版本吗？

### ISSUE THREAD

**Issue by guanJiaPo** [netease-kit/nim-uikit-ios#346]
有oc版本吗？

**Comment by ElfSundae** [comment]
老版本是 OC 的：https://github.com/netease-kit/nim-uikit-ios/tree/uikit_archive
```ruby
pod 'NIMKit', '~> 3.7'
```
如果集成有问题，可以试试我的fork：https://github.com/ElfSundae/NIM_iOS_UIKit
