### ISSUE TITLE
oc项目cocoapods导入

### ISSUE THREAD

**Issue by jhfkf** [netease-kit/nim-uikit-ios#352]
Failed to build module 'NEKitCommonUI'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)', while this compiler is 'Apple Swift version 5.7 (swiftlang-5.7.0.127.4 clang-1400.0.29.50)'). Please select a toolchain which matches the SDK.

**Comment by maghzchenyu** [comment]
Swift 版本兼容问题，已经在新版本中做了Swift版本兼容，如果还有其他问题可以联系云信技术支持或者直接邮件联系我cyn0544@corp.netease.com。
