### ISSUE TITLE
运行项目，报错,Xcode 14.0

### ISSUE THREAD

**Issue by SeongBrave** [netease-kit/nim-uikit-ios#353]
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/10784393/196108296-873da965-e985-41f2-af4a-985fb350afe3.png">

**Comment by SeongBrave** [comment]
<img width="615" alt="image" src="https://user-images.githubusercontent.com/10784393/196133711-010b00ef-08e9-423a-96e0-bd130ec2a16f.png">
使用源码的方式， 好像是Xcode14上才会报错，麻烦看下是什么原因呢

**Comment by Dongshanxu** [comment]
> <img alt="image" width="615" src="https://user-images.githubusercontent.com/10784393/196133711-010b00ef-08e9-423a-96e0-bd130ec2a16f.png">
> 
> 使用源码的方式， 好像是Xcode14上才会报错，麻烦看下是什么原因呢

<img width="798" alt="image" src="https://user-images.githubusercontent.com/15043185/196359563-32390dc3-638a-408f-b8fc-989be3f0eca9.png">
打开podfile中这部分

**Comment by SeongBrave** [comment]
> > <img alt="image" width="615" src="https://user-images.githubusercontent.com/10784393/196133711-010b00ef-08e9-423a-96e0-bd130ec2a16f.png">
> > 使用源码的方式， 好像是Xcode14上才会报错，麻烦看下是什么原因呢
> 
> <img alt="image" width="798" src="https://user-images.githubusercontent.com/15043185/196359563-32390dc3-638a-408f-b8fc-989be3f0eca9.png">
> 
> 打开podfile中这部分

是打开的,也会存在错误的

**Comment by Dongshanxu** [comment]
> > > <img alt="image" width="615" src="https://user-images.githubusercontent.com/10784393/196133711-010b00ef-08e9-423a-96e0-bd130ec2a16f.png">
> > > 使用源码的方式， 好像是Xcode14上才会报错，麻烦看下是什么原因呢
> > 
> > 
> > <img alt="image" width="798" src="https://user-images.githubusercontent.com/15043185/196359563-32390dc3-638a-408f-b8fc-989be3f0eca9.png">
> > 打开podfile中这部分
> 
> 是打开的,也会存在错误的

使用真机编译，目前不支持模拟器

**Comment by Dongshanxu** [comment]
> > > <img alt="image" width="615" src="https://user-images.githubusercontent.com/10784393/196133711-010b00ef-08e9-423a-96e0-bd130ec2a16f.png">
> > > 使用源码的方式， 好像是Xcode14上才会报错，麻烦看下是什么原因呢
> > 
> > 
> > <img alt="image" width="798" src="https://user-images.githubusercontent.com/15043185/196359563-32390dc3-638a-408f-b8fc-989be3f0eca9.png">
> > 打开podfile中这部分
> 
> 是打开的,也会存在错误的


> > > <img alt="image" width="615" src="https://user-images.githubusercontent.com/10784393/196133711-010b00ef-08e9-423a-96e0-bd130ec2a16f.png">
> > > 使用源码的方式， 好像是Xcode14上才会报错，麻烦看下是什么原因呢
> > 
> > 
> > <img alt="image" width="798" src="https://user-images.githubusercontent.com/15043185/196359563-32390dc3-638a-408f-b8fc-989be3f0eca9.png">
> > 打开podfile中这部分
> 
> 是打开的,也会存在错误的

清理一下podfile.lock和pods中的内容，在执行pod install

**Comment by SeongBrave** [comment]
OK，缓存问题，可以了
