### ISSUE TITLE
下载的demo pod文件爆红，编译不了

### ISSUE THREAD

**Issue by KingSering** [netease-kit/nim-uikit-ios#357]
下载的demo pod文件爆红，编译不了
![image](https://user-images.githubusercontent.com/21175003/197735029-33b05410-eeac-4338-994b-f3914d8735bd.png)

**Comment by KingSering** [comment]
没事了，重新 pod 项目后就不报红了

**Comment by maghzchenyu** [comment]
> 没事了，重新 pod install 项目后就不报红了

pod install 没有成功
