### ISSUE TITLE
pod 会话列表和单聊模块后，编译成功，直接崩溃

### ISSUE THREAD

**Issue by KingSering** [netease-kit/nim-uikit-ios#358]
![image](https://user-images.githubusercontent.com/21175003/197951119-9f11a2ea-85b7-4fec-aa8d-7ac825f0574a.png)
![image](https://user-images.githubusercontent.com/21175003/197951206-6b06a7b1-9ec2-4dc1-829a-0e2130eab204.png)

**Comment by KingSering** [comment]
把podfile文件中的库版本 改成最新的 9.2.9 再重新pod install 就不崩溃了

**Comment by maghzchenyu** [comment]
> 把podfile文件中的库版本 改成最新的 9.2.9 再重新pod install 就不崩溃了

Framework 名字又变更，崩溃是因为低版本和高版本引用基础库名字不一致，不指定版本有可能引用到低版本pod 库，名字不一致，导致加载Framework失败。
