### ISSUE TITLE
sdk源码都是swift维护的，可以集成到oc项目里面吗？

### ISSUE THREAD

**Issue by KingSering** [netease-kit/nim-uikit-ios#361]
sdk源码都是swift维护的，可以集成到oc项目里面吗？创建swift的会话列表类newVC继承源码的会话列表类后，无法在oc项目里面调用 swift类newVC，是im源码不支持集成在oc项目里面吗？
![image](https://user-images.githubusercontent.com/21175003/198256985-66ac0e03-6f63-4619-a6ca-327710f264a8.png)
![image](https://user-images.githubusercontent.com/21175003/198257035-f4db445a-0443-401d-ae89-9c98dc99b708.png)

**Comment by maghzchenyu** [comment]
9.4.0 会上传OC接入示例工程，预计2023.3.15发布

> sdk源码都是swift维护的，可以集成到oc项目里面吗？创建swift的会话列表类newVC继承源码的会话列表类后，无法在oc项目里面调用 swift类newVC，是im源码不支持集成在oc项目里面吗？ ![image](https://user-images.githubusercontent.com/21175003/198256985-66ac0e03-6f63-4619-a6ca-327710f264a8.png) ![image](https://user-images.githubusercontent.com/21175003/198257035-f4db445a-0443-401d-ae89-9c98dc99b708.png)
