### ISSUE TITLE
查看源码模式下could not build Objective-C module 'NEChatUIKit

### ISSUE THREAD

**Issue by zhao1zhihui** [netease-kit/nim-uikit-ios#363]
/Users/zhaozhihui/Library/Developer/Xcode/DerivedData/app-aegyskeicngefhcmtztxkxryboyx/Build/Products/Debug-iphonesimulator/NEChatUIKit/NEChatUIKit.framework/Headers/NEChatUIKit-Swift.h:635:38: error: no type or protocol named 'ChatRepoMessageDelegate'
@interface ChatViewModel : NSObject <ChatRepoMessageDelegate, ChatExtendProviderDelegate, NIMChatManagerDelegate, NIMConversationManagerDelegate, NIMSystemNotificationManagerDelegate>
                                     ^
<unknown>:0: error: could not build Objective-C module 'NEChatUIKit'
ChatRepoMessageDelegate 这个找不到但是我可以点进取怎么修复

**Comment by seanLee** [comment]
meet the same error

**Comment by maghzchenyu** [comment]
9.4.0 已解决，预计2023.3.15发布
