### ISSUE TITLE
阿语带有emoji显示错误

### ISSUE THREAD

**Issue by iLiuChang** [netease-kit/nim-uikit-ios#365]
https://user-images.githubusercontent.com/13009406/203292858-2dd5fb44-4488-4794-a141-ad36a43a186e.MP4

**Comment by maghzchenyu** [comment]
https://user-images.githubusercontent.com/5235791/221844142-80d337d1-373f-4728-9d67-96492e3f9283.mp4

**Comment by iLiuChang** [comment]
如果是阿语和其他语言混在一起, 应该是系统无法确定语言方向了, 我统一改成从左开始就可以了
