### ISSUE TITLE
xcode14.3 swift版本不同报错 9.4.0有问题，9.3.0是好的，BUILD_LIBRARY_FOR_DISTRIBUTION设置也是一样的。xcode14.2是好的

### ISSUE THREAD

**Issue by LMgod** [netease-kit/nim-uikit-ios#371]
Failed to build module 'NECoreIMKit'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.7.1 (swiftlang-5.7.1.135.3 clang-1400.0.29.51)', while this compiler is 'Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)'). Please select a toolchain which matches the SDK.

**Comment by seanLee** [comment]
你好，想麻烦问一下解决这个问题了吗？我15.X的Xcode也报错了

**Comment by seanLee** [comment]
是不是要升级云信SDK的版本
