### ISSUE TITLE
mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')

### ISSUE THREAD

**Issue by qingEmail** [netease-kit/nim-uikit-ios#379]
这个要怎么解决，M1芯片

**Comment by adongdev** [comment]
Undefined symbol: _AAChartLineDashStyleTypeLongDashDot

Undefined symbol: _AAChartLineDashStyleTypeLongDashDotDot

Undefined symbol: _AAChartSymbolStyleTypeBorderBlank

Undefined symbol: _AAChartTypeLine

Undefined symbol: _CSToastPositionCenter

Undefined symbol: _NIMKitEventNameTapContent

Undefined symbol: _NIMKitEventNameTapLabelLink

Undefined symbol: _OBJC_CLASS_$_AAChartModel

Undefined symbol: _OBJC_CLASS_$_AAChartView

Undefined symbol: _OBJC_CLASS_$_AACrosshair

Undefined symbol: _OBJC_CLASS_$_AALabel

Undefined symbol: _OBJC_CLASS_$_AALineStyle

Undefined symbol: _OBJC_CLASS_$_AAPlotLinesElement

Undefined symbol: _OBJC_CLASS_$_AASeriesElement

Undefined symbol: _OBJC_CLASS_$_AAStyle

Undefined symbol: _OBJC_CLASS_$_AFHTTPRequestSerializer

Undefined symbol: _OBJC_CLASS_$_AFHTTPSessionManager

Undefined symbol: _OBJC_CLASS_$_AFJSONRequestSerializer

Undefined symbol: _OBJC_CLASS_$_AFJSONResponseSerializer

Undefined symbol: _OBJC_CLASS_$_AFNetworkReachabilityManager

Undefined symbol: _OBJC_CLASS_$_AFSecurityPolicy

Undefined symbol: _OBJC_CLASS_$_FMDatabase

Undefined symbol: _OBJC_CLASS_$_FSCalendar

Undefined symbol: _OBJC_CLASS_$_IAPHelper

Undefined symbol: _OBJC_CLASS_$_IAPShare

Undefined symbol: _OBJC_CLASS_$_IQKeyboardManager

Undefined symbol: _OBJC_CLASS_$_MBProgressHUD

Undefined symbol: _OBJC_CLASS_$_MJRefreshBackStateFooter

Undefined symbol: _OBJC_CLASS_$_MJRefreshNormalHeader

Undefined symbol: _OBJC_CLASS_$_NIMAdvanceMenu

Undefined symbol: _OBJC_CLASS_$_NIMCellLayoutConfig

Undefined symbol: _OBJC_CLASS_$_NIMKit

Undefined symbol: _OBJC_CLASS_$_NIMKitEvent

Undefined symbol: _OBJC_CLASS_$_NIMKitInfo

Undefined symbol: _OBJC_CLASS_$_NIMKitLocationPoint

Undefined symbol: _OBJC_CLASS_$_NIMKitUtil

Undefined symbol: _OBJC_CLASS_$_NIMLocationViewController

Undefined symbol: _OBJC_CLASS_$_NIMMediaItem

Undefined symbol: _OBJC_CLASS_$_NIMMessageCell

Undefined symbol: _OBJC_CLASS_$_NIMMessageModel

Undefined symbol: _OBJC_CLASS_$_NIMSessionListViewController

Undefined symbol: _OBJC_CLASS_$_NIMSessionMessageContentView

Undefined symbol: _OBJC_CLASS_$_NIMSessionViewController

Undefined symbol: _OBJC_CLASS_$_SDImageCache

Undefined symbol: _OBJC_CLASS_$_SDWebImageManager

Undefined symbol: _OBJC_CLASS_$_SVProgressHUD

Undefined symbol: _OBJC_METACLASS_$_NIMAdvanceMenu

Undefined symbol: _OBJC_METACLASS_$_NIMCellLayoutConfig

Undefined symbol: _OBJC_METACLASS_$_NIMSessionListViewController

Undefined symbol: _OBJC_METACLASS_$_NIMSessionMessageContentView

Undefined symbol: _OBJC_METACLASS_$_NIMSessionViewController

Linker command failed with exit code 1 (use -v to see invocation)

以上报的一堆错，摸索了几个小时也没解决，终于想到在问题题里来看看，

参照：https://stackoverflow.com/questions/63607158/xcode-building-for-ios-simulator-but-linking-in-an-object-file-built-for-ios-f/63955114#63955114

在podfile最后添加以下配置，老项目我就运行成功了！

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end
