### ISSUE TITLE
xcode16  启动崩溃

### ISSUE THREAD

**Issue by huqizi4570** [netease-kit/nim-uikit-ios#405]
dyld[5768]: Symbol not found: __ZN5swift34swift50override_conformsToProtocolEPKNS_14TargetMetadataINS_9InProcessEEEPKNS_24TargetProtocolDescriptorIS1_EEPFPKNS_18TargetWitnessTableIS1_EES4_S8_E
  Referenced from: <4D18751A-5642-307E-A67B-DC10A88B0788> /private/var/containers/Bundle/Application/2BC2FE9C-6F54-4185-8F8E-BA20D7F0C0C4/app.app/Frameworks/NEAISearchKit.framework/NEAISearchKit
  Expected in:     <513DD642-E2B1-33C8-BAAC-7D56CA94D6DD> /private/var/containers/Bundle/Application/2BC2FE9C-6F54-4185-8F8E-BA20D7F0C0C4/app.app/Frameworks/Lottie.framework/Lottie

**Comment by huqizi4570** [comment]
可以把NEContactUIKit这个中的.podspec  引用NECommonUIKit 指定版本去掉吗 ？   目前有冲突，其他引用的是9.7.2。 这个是指定了9.7.0， 我要修改某些布局。  麻烦了

**Comment by shine2008** [comment]
已修复
