### ISSUE TITLE
气泡效果有bug

### ISSUE THREAD

**Issue by coneycode** [netease-kit/nim-uikit-ios#76]
测试机型7plus。
最开始点击进去的时候气泡效果宽度不对。文字超出气泡范围，但是上下滑动tableView对cell重绘后恢复正常。

**Comment by xiangwangfeng** [comment]
具体 NIMKit 什么版本，重现现场和重现条件请列一下

**Comment by coneycode** [comment]
最新版。三天前clone的。
安装完不做任何修改，直接编译打开就会出现该现象。

**Comment by chrisray108** [comment]
用的是仓库里的 Example 工程？

**Comment by coneycode** [comment]
是的。clone下来以后pod install 后直接运行。你们那没出现这个问题嘛？

**Comment by moyifan** [comment]
是的，pod完直接使用就有这个问题，很久就有了，一直没有修复

**Comment by chrisray108** [comment]
试了下没有复现呢，确定是 Example 工程？  pod install 的日志可以发下看看吗？

**Comment by ghostlordstar** [comment]
是的， 我也发现了，改了一下，虽然一进入时可以，但是点击头像跳转其他界面，返回到会话界面又成这样了，刷新一下就好了，暂时只发现iOS 11上会有这样的问题，其他系统版本没发现

**Comment by chrisray108** [comment]
老的版本会有这个兼容问题，线上最新的是2.0.0的，确认下你们组件的版本？

**Comment by ghostlordstar** [comment]
好的，我检查一下

发自我的 iPhone

在 2017年11月7日，下午1:42，chrisray108 <notifications@github.com<mailto:notifications@github.com>> 写道：


老的版本会有这个兼容问题，线上最新的是2.0.0的，确认下你们组件的版本？

**Comment by ghostlordstar** [comment]
因为我们业务比较简单，所以重写了UI组件😄

发自我的 iPhone

在 2017年11月13日，下午11:00，vic <notifications@github.com<mailto:notifications@github.com>> 写道：


我就是升级2.0以后出现的这个问题。。7 plus上会出现，7不会出现。

**Comment by chrisray108** [comment]
@coneycode  我这里复现不出呢，用的 Example 的代码。你能给个必现的 demo 吗方便我排查下问题

**Comment by coneycode** [comment]
可是，我真的就是从github上clone下来，一行没改就这样了。。。而且看上面的样子，不止我一个人出现这个问题了。。plus上会有这个问题。

**Comment by WangYue666666** [comment]
我也出现了 这样的问题     今天集成 就出现 发送的 消息 和气泡 对应不上  ，下拉刷新下 就好了 。。很是郁闷  手机是 iOS11  6P   但是 你们dome  里面 没有这个问题 。 我不知道 问题出在哪了！！！！

**Comment by fdyhgjg** [comment]
关于这个问题  就是ios表格的原因。
因为最近也做了一个聊天app 用到了NIMKIT 发现跟你同一个问题 自己改了这个kit的源码
进入NIMSessionViewController的m文件，找到- (void)setupTableView这个创建表格的方法 在表格add到self.view之前加一句判断就行
if (@available(iOS 11.0, *)) {
        self.tableView.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;
       self.tableView.estimatedRowHeight = 0;
       self.tableView.estimatedSectionHeaderHeight = 0;
       self.tableView.estimatedSectionFooterHeight = 0;
 }
虽然这样可以解决 但是毕竟就用pod集成进来的 下次pod update就GG了 所以 希望网易云的大佬们考虑下更新下pod代码

**Comment by applejian** [comment]
扩展 runtime 方式 添加

**Comment by applejian** [comment]
#import "NIMSessionViewController.h"

@interface NIMSessionViewController (NIMKIT)
@property (nonatomic, strong)  UITableView *tableView;

@end

@implementation NIMSessionViewController (NIMKIT)

+ (void)load
{
    method_exchangeImplementations(class_getInstanceMethod(self,@selector(setupTableView)),
                                   class_getInstanceMethod(self,@selector(ys_setupTableView)));
}

- (void)ys_setupTableView
{
    [self ys_setupTableView];
    
    if (@available(iOS 11.0, *)) {
        self.tableView.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;
        self.tableView.estimatedRowHeight = 0;
        self.tableView.estimatedSectionHeaderHeight = 0;
        self.tableView.estimatedSectionFooterHeight = 0;
    }
}

@end

**Comment by zsading** [comment]
有相同的问题

**Comment by GavinCarter1991** [comment]
还是有这个问题呀

**Comment by neverGiveUpYourDream** [comment]
直接继承，然后添加fdyhgjg 的代码不就好了么？

**Comment by neverGiveUpYourDream** [comment]
> 关于这个问题 就是ios表格的原因。
> 因为最近也做了一个聊天app 用到了NIMKIT 发现跟你同一个问题 自己改了这个kit的源码
> 进入NIMSessionViewController的m文件，找到- (void)setupTableView这个创建表格的方法 在表格add到self.view之前加一句判断就行
> if (@available(iOS 11.0, *)) {
> self.tableView.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;
> self.tableView.estimatedRowHeight = 0;
> self.tableView.estimatedSectionHeaderHeight = 0;
> self.tableView.estimatedSectionFooterHeight = 0;
> }
> 虽然这样可以解决 但是毕竟就用pod集成进来的 下次pod update就GG了 所以 希望网易云的大佬们考虑下更新下pod代码

新的系统版本如果带上> self.tableView.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever; 这句话， table 的偏移就会有问题，去掉第一句话只带后面的就都 Ok
